# Generated by Django 4.2.7 on 2024-02-26 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("experiments", "0066_alter_experimentsession_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeoutTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delay",
                    models.PositiveIntegerField(
                        help_text="The amount of time in seconds to fire this trigger."
                    ),
                ),
                (
                    "total_num_triggers",
                    models.IntegerField(
                        default=1, help_text="The number of times to fire this trigger"
                    ),
                ),
                (
                    "end_conversation",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to end the conversation after all the triggers have expired",
                    ),
                ),
                (
                    "last_triggered",
                    models.DateTimeField(
                        help_text="The last time this trigger was fired", null=True
                    ),
                ),
                (
                    "trigger_count",
                    models.IntegerField(
                        default=0,
                        help_text="The number of times this trigger was fired",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeout_triggers",
                        to="experiments.experiment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
