# Generated by Django 4.2.7 on 2024-02-27 09:01

from django.db import migrations
from django_celery_beat.models import IntervalSchedule


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

