# Generated by Django 4.2.7 on 2024-02-27 09:01

from django.db import migrations
from django_celery_beat.models import IntervalSchedule


def create_periodic_task(apps, schema_editor):
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=10,
        period="seconds",
    )
    PeriodicTask.objects.get_or_create(
        name="events.tasks.enqueue_timed_out_events",
        task="apps.events.tasks.enqueue_timed_out_events",
        interval=schedule,
    )


def delete_periodic_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name="events.tasks.enqueue_timed_out_events").delete()


class Migration(migrations.Migration):
    dependencies = []

    operations = [migrations.RunPython(create_periodic_task, delete_periodic_task)]
