# Generated by Django 4.2.7 on 2024-04-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventlog_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("log", "Log the last message"),
                    ("end_conversation", "End the conversation"),
                    ("summarize", "Summarize the conversation"),
                    ("send_message_to_bot", "Prompt the bot to message the user"),
                ]
            ),
        ),
    ]
