# Generated by Django 4.2.7 on 2024-04-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventaction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statictrigger',
            name='type',
            field=models.CharField(choices=[('conversation_end', 'The conversation ends'), ('last_timeout', 'The last timeout occurs'), ('human_safety_layer_triggered', 'The safety layer is triggered by a human'), ('bot_safety_layer_triggered', 'The safety layer is triggered by a bot'), ('conversation_start', 'A new conversation is started'), ('new_human_message', 'A new human message is received'), ('new_bot_message', 'A new bot message is received'), ('participant_joined', 'A new participant joined the experiment')], db_index=True),
        ),
    ]
