# Generated by Django 4.2.7 on 2024-04-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventaction_action_type_scheduledmessage'),
    ]

