# Generated by Django 4.2.11 on 2024-05-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_create_scheduled_message_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='custom_schedule_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
