# Generated by Django 4.2.7 on 2024-05-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_create_scheduled_message_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='preference_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
