# Generated by Django 4.2.11 on 2024-06-10 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        ('events', '0010_alter_eventaction_action_type'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='scheduledmessage',
                    name='participant',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schduled_messages', to='participants.participant'),
                ),
            ],
        ),
    ]
