# Generated by Django 4.2.7 on 2024-02-27 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0010_alter_eventaction_action_type')
    ]

