# Generated by Django 4.2.11 on 2024-07-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_no_activity_pings_to_events_20240709_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='action',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='events.eventaction'),
        ),
    ]
