# Generated by Django 4.2.14 on 2024-07-25 19:14

from django.db import migrations, models

from apps.utils.slug import get_next_unique_id


def populate_scheduled_message_name(apps, schema_editor):
    ScheduledMessage = apps.get_model("events", "ScheduledMessage")

    for schedule in ScheduledMessage.objects.filter(external_id="").select_related("action"):
        name = schedule.custom_schedule_params.get("name") or schedule.action.params["name"]
        inputs = [name, schedule.experiment_id, schedule.participant_id]
        schedule.external_id = get_next_unique_id(
            ScheduledMessage, inputs, "external_id", length=5, model_instance=schedule
        )
        schedule.save()


class Migration(migrations.Migration):
    dependencies = [
        ("experiments", "0084_participant_platform_alter_participant_options_and_more"),
        ("events", "0013_alter_scheduledmessage_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmessage",
            name="external_id",
            field=models.CharField(
                default="",
                help_text="A unique identifier for the scheduled message",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_scheduled_message_name, migrations.RunPython.noop, elidable=True),
        migrations.AlterUniqueTogether(
            name="scheduledmessage",
            unique_together={("experiment", "participant", "external_id")},
        ),
    ]
