# Generated by Django 4.2.15 on 2024-08-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_move_schedule_messages_off_periodic_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='action',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='events.eventaction'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='last_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='next_trigger_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
