# Generated by Django 5.1 on 2024-09-06 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_scheduledmessage_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statictrigger',
            name='working_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='events.statictrigger'),
        ),
        migrations.AddField(
            model_name='timeouttrigger',
            name='working_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='events.timeouttrigger'),
        ),
    ]
