# Generated by Django 5.1 on 2024-09-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_statictrigger_working_version_and_more'),
    ]

