# Generated by Django 5.1 on 2024-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_statictrigger_working_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statictrigger',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
