# Generated by Django 5.1 on 2024-09-11 13:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0017_statictrigger_working_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statictrigger",
            name="trigger_arg",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="statictrigger",
            name="trigger_op",
            field=models.CharField(
                blank=True,
                choices=[("eq", "Equals"), ("ne", "Not Equals"), ("in", "In")],
            ),
        ),
    ]
