# Generated by Django 5.1 on 2024-10-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_update_timed_out_events_trigger_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='statictrigger',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeouttrigger',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
