# Generated by Django 5.1.2 on 2025-01-20 07:04

"""
Updates the time_period field in EventAction params where "minutes" was used to "mins". This is to make
the field compatible with how minutes are specified in Postgres. See apps/utils/django_db.py.
"""

from django.db import migrations
from apps.events.models import EventActionType

def _change_minutes_to_mins(apps, schema_editor):
    EventAction = apps.get_model("events", "EventAction")
    updated_actions = []
    for action in EventAction.objects.only("params").filter(
        action_type=EventActionType.SCHEDULETRIGGER,
        params__time_period="minutes"
    ):
        action.params["time_period"] = "mins"
        updated_actions.append(action)
    
    EventAction.objects.bulk_update(updated_actions, ["params"])

def _change_mins_to_minutes(apps, schema_editor):
    EventAction = apps.get_model("events", "EventAction")
    updated_actions = []
    for action in EventAction.objects.only("params").filter(
        action_type=EventActionType.SCHEDULETRIGGER,
        params__time_period="mins"
    ):
        action.params["time_period"] = "minutes"
        updated_actions.append(action)
    
    EventAction.objects.bulk_update(updated_actions, ["params"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_statictrigger_is_archived_timeouttrigger_is_archived'),
    ]

    operations = [
        migrations.RunPython(code=_change_minutes_to_mins, reverse_code=_change_mins_to_minutes),
    ]
