# Generated by Django 5.1.5 on 2025-06-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_scheduledmessage_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statictrigger',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeouttrigger',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
