# Generated by Django 5.1.5 on 2025-07-01 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_statictrigger_is_active_timeouttrigger_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessageAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_number', models.IntegerField()),
                ('attempt_number', models.IntegerField()),
                ('attempt_result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('log_message', models.TextField(blank=True, null=True)),
                ('trace_info', models.JSONField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='events.scheduledmessage')),
            ],
            options={
                'unique_together': {('scheduled_message', 'trigger_number', 'attempt_number')},
            },
        ),
    ]
