# Generated by Django 5.1.5 on 2026-01-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_scheduledmessageattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statictrigger',
            name='type',
            field=models.CharField(choices=[('conversation_end', 'The conversation has ended (user, bot, api or admin)'), ('conversation_ended_by_user', 'The conversation is ended by the user'), ('conversation_ended_by_bot', 'The conversation is ended by the bot'), ('conversation_ended_via_api', 'The conversation is ended via the API'), ('conversation_ended_manually', 'The conversation is manually ended by an admin'), ('last_timeout', 'The last timeout occurs'), ('human_safety_layer_triggered', 'The safety layer is triggered by a human'), ('bot_safety_layer_triggered', 'The safety layer is triggered by a bot'), ('conversation_start', 'A new conversation is started'), ('new_human_message', 'A new human message is received'), ('new_bot_message', 'A new bot message is received'), ('participant_joined', 'A new participant joined the experiment')], db_index=True),
        ),
    ]
