# Generated by Django 5.1.5 on 2025-11-24 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_scheduledmessageattempt'),
        ('participants', '0001_move_models_from_experiments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schduled_messages', to='participants.participant'),
        ),
    ]
