# Generated by Django 5.1.15 on 2026-01-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_scheduledmessageattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventaction',
            name='action_type',
            field=models.CharField(choices=[('log', 'Log the last message'), ('end_conversation', 'End the conversation'), ('send_message_to_bot', 'Prompt the bot to message the user'), ('schedule_trigger', 'Trigger a schedule'), ('pipeline_start', 'Start a pipeline')]),
        ),
    ]
