# Generated by Django 5.1.15 on 2026-02-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_remove_summarize_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statictrigger',
            name='type',
            field=models.CharField(choices=[('conversation_end', 'The conversation has ended (by any means)'), ('conversation_ended_by_user', 'The conversation is ended by the participant'), ('conversation_ended_by_bot', 'The conversation is ended by the bot'), ('conversation_ended_via_api', 'The conversation is ended via the API'), ('conversation_ended_by_event', 'The conversation is ended by an event'), ('conversation_ended_manually', 'The conversation is manually ended by an admin'), ('last_timeout', 'The last timeout occurs'), ('conversation_start', 'A new conversation is started'), ('new_human_message', 'A new human message is received'), ('new_bot_message', 'A new bot message is received'), ('participant_joined', 'A new participant joined the experiment')], db_index=True),
        ),
    ]
