# Generated by Django 5.1.15 on 2026-02-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_statictrigger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeouttrigger',
            name='trigger_from_first_message',
            field=models.BooleanField(default=False, help_text='When enabled, the timeout delay is calculated from the first message in the conversation rather than the most recent.'),
        ),
        migrations.AlterField(
            model_name='timeouttrigger',
            name='delay',
            field=models.PositiveIntegerField(help_text='Seconds to wait before triggering action'),
        ),
    ]
