# Generated by Django 5.1.15 on 2026-02-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_statictrigger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeouttrigger',
            name='trigger_from_first_message',
            field=models.BooleanField(default=False, help_text='If True, the timeout delay is calculated from the first human message instead of the last.'),
        ),
    ]
