# Generated by Django 5.2.16 on 2026-09-03 00:46

import apps.experiments.versioning
import apps.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_timeouttrigger_config_changed_at"),
        ("experiments", "0150_alter_experiment_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_logs",
                to="experiments.experimentsession",
            ),
        ),
        migrations.CreateModel(
            name="ScheduledTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trigger_date",
                    models.DateField(
                        help_text="The date on which the trigger should fire (YYYY-MM-DD)"
                    ),
                ),
                (
                    "trigger_time",
                    models.TimeField(
                        help_text="The local time at which the trigger should fire (HH:MM)"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        help_text="IANA timezone name in which date/time are interpreted",
                        max_length=64,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        help_text="The trigger moment converted to UTC at save time, used to determine when the trigger is due"
                    ),
                ),
                ("fired_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_trigger",
                        to="events.eventaction",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_triggers",
                        to="experiments.experiment",
                    ),
                ),
                (
                    "working_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="events.scheduledtrigger",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                apps.utils.models.VersioningMixin,
                apps.experiments.versioning.VersionsMixin,
            ),
        ),
    ]
