# Generated by Django 5.2.16 on 2026-09-23 12:08

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("events", "0028_scheduledtrigger_active_session_window_days"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="scheduledmessage",
            index=models.Index(fields=["updated_at", "id"], name="schedmessage_updated_at_id_idx"),
        ),
    ]
