# Generated by Django 5.2.16 on 2026-09-30 12:48

from django.db import migrations
from django.db.models import Q

END_TRIGGER_TYPES = [
    "conversation_end",
    "conversation_ended_by_user",
    "conversation_ended_by_bot",
    "conversation_ended_via_api",
    "conversation_ended_by_event",
    "conversation_ended_manually",
]


def remove_end_conversation_end_triggers(apps, schema_editor):
    StaticTrigger = apps.get_model("events", "StaticTrigger")
    EventAction = apps.get_model("events", "EventAction")
    EventLog = apps.get_model("events", "EventLog")
    ContentType = apps.get_model("contenttypes", "ContentType")

    matching = StaticTrigger.objects.filter(type__in=END_TRIGGER_TYPES, action__action_type="end_conversation")
    triggers = list(
        StaticTrigger.objects.filter(Q(id__in=matching) | Q(working_version__in=matching)).values_list(
            "id", "action_id"
        )
    )
    if not triggers:
        return

    trigger_ids, action_ids = zip(*triggers, strict=True)
    EventLog.objects.filter(
        content_type__in=ContentType.objects.filter(app_label="events", model="statictrigger"),
        object_id__in=trigger_ids,
    ).delete()
    EventAction.objects.filter(id__in=action_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0028_scheduledtrigger_active_session_window_days"),
    ]

    operations = [
        migrations.RunPython(remove_end_conversation_end_triggers, migrations.RunPython.noop, elidable=True),
    ]
