# Generated by Django 5.2.16 on 2026-09-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0028_alter_eventlog_session_scheduledtrigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledtrigger",
            name="active_session_window_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Only fire against sessions with user activity in the last N days. Leave blank to target all open sessions.",
                null=True,
            ),
        ),
    ]
