# Generated by Django 5.1.5 on 2025-06-19 09:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('teams', '0007_create_commcare_connect_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dashboardcache',
            name='unique_cache_per_team_key',
        ),
        migrations.RemoveConstraint(
            model_name='dashboardfilter',
            name='unique_filter_per_user_team',
        ),
        migrations.RemoveConstraint(
            model_name='dashboardmetricssnapshot',
            name='unique_snapshot_per_team_date',
        ),
        migrations.RenameIndex(
            model_name='dashboardcache',
            new_name='dashboard_d_team_id_fee32a_idx',
            old_name='dashboard_d_team_id_9c8f4f_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardfilter',
            new_name='dashboard_d_team_id_76f6f0_idx',
            old_name='dashboard_d_team_id_e58b90_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardmetricssnapshot',
            new_name='dashboard_d_team_id_cfc80c_idx',
            old_name='dashboard_d_team_id_48b3a6_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardmetricssnapshot',
            new_name='dashboard_d_date_9abee0_idx',
            old_name='dashboard_d_date_16d63e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dashboardcache',
            unique_together={('team', 'cache_key')},
        ),
        migrations.AlterUniqueTogether(
            name='dashboardfilter',
            unique_together={('team', 'user', 'filter_name')},
        ),
        migrations.AlterUniqueTogether(
            name='dashboardmetricssnapshot',
            unique_together={('team', 'date')},
        ),
    ]
