# Generated by Django 4.2.11 on 2024-06-11 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0080_remove_experiment_tools_enabled_and_more'),
        ('pipelines', '0002_pipelinerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to='experiments.experimentsession'),
        ),
    ]
