# Generated by Django 5.1 on 2024-10-17 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_pipelinechathistory_pipelinechatmessages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='working_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pipelines.node'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='working_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pipelines.pipeline'),
        ),
    ]
