# Generated by Django 5.1 on 2024-10-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_pipelinechathistory_pipelinechatmessages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinechatmessages',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
