# Generated by Django 5.1 on 2024-10-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_pipelinechathistory_pipelinechatmessages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinechathistory',
            name='token_limit',
            field=models.IntegerField(default=8192),
        ),
        migrations.CreateModel(
            name='PipelineChatHistorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='pipelines.pipelinechathistory')),
                ('messages', models.ManyToManyField(related_name='summaries', to='pipelines.pipelinechatmessages')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
