# Generated by Django 5.1 on 2024-10-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_pipelinechathistory_pipelinechatmessages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinechathistory',
            name='token_limit',
            field=models.IntegerField(default=8192),
        ),
        migrations.AddField(
            model_name='pipelinechatmessages',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
