# Generated by Django 5.1 on 2024-10-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0007_pipelinechatmessages_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinechatmessages',
            name='node_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
