# Generated by Django 5.1.2 on 2024-11-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0008_pipelinechatmessages_node_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinechathistory",
            name="type",
            field=models.CharField(
                choices=[
                    ("node", "Node"),
                    ("named", "Named"),
                    ("global", "Global"),
                    ("none", "No History"),
                ],
                max_length=10,
            ),
        ),
    ]
