# Generated by Django 5.1.2 on 2024-12-31 15:54

from django.db import migrations

def _add_default_name_to_nodes(apps, schema_editor):
    Pipeline = apps.get_model("pipelines", "Pipeline")
    Node = apps.get_model("pipelines", "Node")

    for pipeline in Pipeline.objects.all():
        nodes = pipeline.node_set.all()
        data = pipeline.data
        for node in nodes:
            if "name" in node.params:
                continue

            name = node.flow_id

            if node.type == "StartNode":
                name = "start"
            if node.type == "EndNode":
                name = "end"

            node.params["name"] = name
            node.save()



def _remove_node_names(apps, schema_editor):
    Pipeline = apps.get_model("pipelines", "Pipeline")
    Node = apps.get_model("pipelines", "Node")

    for pipeline in Pipeline.objects.all():
        nodes = pipeline.node_set.all()
        data = pipeline.data

        for node in nodes:
            if "name" in node.params:
                del node.params["name"]
                node.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0010_auto_20241127_2042'),
    ]

    operations = [
        migrations.RunPython(_add_default_name_to_nodes, reverse_code=_remove_node_names)
    ]
