# Generated by Django 5.1.5 on 2025-04-28 12:18

from django.db import migrations
from apps.pipelines.nodes.nodes import RouterNode, StaticRouterNode

def _set_default_key_value(apps, schema_editor):
    """Populate the default keyword index for router nodes."""
    Node = apps.get_model('pipelines', 'Node')
    router_types = [StaticRouterNode.__name__, RouterNode.__name__]

    updates = []
    for node in Node.objects.filter(type__in=router_types).iterator(100):
        if "defaultKeywordIndex" in node.params:
            # Do not remove the `defaultKeywordIndex` key for backward compatibility
            node.params["default_keyword_index"] = node.params["defaultKeywordIndex"]
        else:
            node.params["default_keyword_index"] = 0
        updates.append(node)

    Node.objects.bulk_update(updates, ["params"])


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0014_set_default_history_mode'),
    ]

    operations = [migrations.RunPython(_set_default_key_value, reverse_code=migrations.RunPython.noop)]
