# Generated by Django 5.1.5 on 2025-05-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0015_set_default_key_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PipelineRun',
        ),
    ]
