# Generated by Django 5.1.5 on 2025-05-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0016_delete_pipelinerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinechatmessages',
            name='compression_marker',
            field=models.CharField(blank=True, choices=[('summarize', 'Summarize'), ('truncate_tokens', 'Truncate Tokens'), ('max_history_length', 'Max History Length')], max_length=32),
        ),
        migrations.RunSQL("UPDATE pipelines_pipelinechatmessages SET compression_marker = 'summarize' WHERE summary IS NOT NULL AND summary != ''"),
    ]
