# Generated by Django 5.1.5 on 2025-10-23 11:10

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0019_populate_generate_citations_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='params',
            field=apps.utils.fields.SanitizedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='data',
            field=apps.utils.fields.SanitizedJSONField(),
        ),
    ]
