# Generated by Django 5.1.5 on 2025-11-19 09:10

from django.db import migrations


def migrate_collection_index_id_to_ids(apps, schema_editor):
    """Migrate collection_index_id to collection_index_ids (as a list)"""
    Node = apps.get_model("pipelines", "Node")

    nodes_to_update = []
    for idx, node in enumerate(Node.objects.filter(type="LLMResponseWithPrompt").iterator(100)):
        # If the node has a collection_index_id, convert it to a list
        if "collection_index_id" in node.params and node.params["collection_index_id"]:
            node.params["collection_index_ids"] = [node.params["collection_index_id"]]
            # Remove the old field
            del node.params["collection_index_id"]
            nodes_to_update.append(node)
        elif "collection_index_id" in node.params:
            # Remove the old field even if it's None/empty
            del node.params["collection_index_id"]
            # Set to empty list if not already set
            if "collection_index_ids" not in node.params:
                node.params["collection_index_ids"] = []
            nodes_to_update.append(node)

        if idx % 100 == 0 and nodes_to_update:
            Node.objects.bulk_update(nodes_to_update, ["params"])
            nodes_to_update = []

    # Update any remaining nodes
    if nodes_to_update:
        Node.objects.bulk_update(nodes_to_update, ["params"])


def reverse_migration(apps, schema_editor):
    """Reverse the migration by converting collection_index_ids back to collection_index_id"""
    Node = apps.get_model("pipelines", "Node")

    nodes_to_update = []
    for idx, node in enumerate(Node.objects.filter(type="LLMResponseWithPrompt").iterator(100)):
        if "collection_index_ids" in node.params:
            # Take the first ID if it exists, otherwise set to None
            collection_ids = node.params.get("collection_index_ids", [])
            if collection_ids:
                node.params["collection_index_id"] = collection_ids[0]
            else:
                node.params["collection_index_id"] = None
            # Remove the new field
            del node.params["collection_index_ids"]
            nodes_to_update.append(node)

        if idx % 100 == 0 and nodes_to_update:
            Node.objects.bulk_update(nodes_to_update, ["params"])
            nodes_to_update = []

    # Update any remaining nodes
    if nodes_to_update:
        Node.objects.bulk_update(nodes_to_update, ["params"])


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0020_alter_node_params_alter_pipeline_data"),
    ]

    operations = [
        migrations.RunPython(migrate_collection_index_id_to_ids, reverse_migration),
    ]
