# Generated by Django 5.1.5 on 2025-12-10 08:16

from django.db import migrations


def fix_collection_index_ids_type(apps, _schema_editor):
    """Convert string IDs in collection_index_ids to integers"""
    Node = apps.get_model("pipelines", "Node")

    nodes_to_update = []
    for node in Node.objects.filter(type="LLMResponseWithPrompt").iterator(100):
        if "collection_index_ids" in node.params:
            collection_index_ids = node.params["collection_index_ids"]

            # Only process if it's a list
            if isinstance(collection_index_ids, list):
                # Convert any string values to integers
                converted_ids = []
                needs_update = False

                for id_value in collection_index_ids:
                    if isinstance(id_value, str):
                        try:
                            # Convert string to integer
                            converted_ids.append(int(id_value))
                            needs_update = True
                        except (ValueError, TypeError):
                            # If conversion fails, skip this value
                            pass
                    elif isinstance(id_value, int):
                        # Already an integer, keep it
                        converted_ids.append(id_value)

                # Only update if we made changes
                if needs_update:
                    node.params["collection_index_ids"] = converted_ids
                    nodes_to_update.append(node)

        # Batch update when buffer reaches 100 items
        if len(nodes_to_update) >= 100:
            Node.objects.bulk_update(nodes_to_update, ["params"])
            nodes_to_update = []

    # Update any remaining nodes
    if nodes_to_update:
        Node.objects.bulk_update(nodes_to_update, ["params"])


def reverse_migration(apps, _schema_editor):
    """Reverse is a no-op since we're just fixing data types"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0021_migrate_collection_index_to_list"),
    ]

    operations = [
        migrations.RunPython(fix_collection_index_ids_type, reverse_migration),
    ]
