# Generated by Django 5.1.5 on 2025-12-18 12:12

from django.db import migrations

def _convert_keywords_to_lower(apps, schema_editor):
    Node = apps.get_model('pipelines', 'Node')
    nodes_to_update = []
    queryset = Node.objects.filter(type__in=["RouterNode", "StaticRouterNode"]).iterator(chunk_size=100)
    for idx, node in enumerate(queryset):
        if "keywords" in node.params:
            node.params["keywords"] = [kw.lower() for kw in node.params["keywords"]]
            nodes_to_update.append(node)
        
        if idx == 100:
            Node.objects.bulk_update(nodes_to_update, ['params'])
            nodes_to_update = []

    if len(nodes_to_update) > 0:
        Node.objects.bulk_update(nodes_to_update, ['params'])

class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0022_fix_collection_index_ids_type'),
    ]

    operations = [
        migrations.RunPython(_convert_keywords_to_lower, reverse_code=migrations.RunPython.noop),
    ]
