# Generated by Django 5.1.5 on 2026-01-27

from django.db import migrations


def _convert_keywords_to_upper(apps, schema_editor):
    Node = apps.get_model('pipelines', 'Node')
    nodes_to_update = []
    queryset = Node.objects.filter(type__in=["RouterNode", "StaticRouterNode"]).iterator(chunk_size=100)
    for node in queryset:
        if "keywords" in node.params:
            node.params["keywords"] = [kw.upper() for kw in node.params.get("keywords", []) or []]
            nodes_to_update.append(node)

        if len(nodes_to_update) >= 100:
            Node.objects.bulk_update(nodes_to_update, ['params'])
            nodes_to_update = []

    if len(nodes_to_update) > 0:
        Node.objects.bulk_update(nodes_to_update, ['params'])


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0023_make_router_keywords_lower'),
    ]

    operations = [
        migrations.RunPython(_convert_keywords_to_upper, reverse_code=migrations.RunPython.noop),
    ]
