# Generated by Django 5.2.13 on 2026-06-17 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0014_alter_toolresources_extra'),
        ('documents', '0015_collection_create_version_task_id'),
        ('experiments', '0144_remove_experiment_survey_fields_state'),
        ('pipelines', '0025_cleanup_stale_custom_action_refs'),
        ('service_providers', '0057_add_claude_fable_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='assistants.openaiassistant'),
        ),
        migrations.AddField(
            model_name='node',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_nodes', to='documents.collection'),
        ),
        migrations.AddField(
            model_name='node',
            name='collection_indexes',
            field=models.ManyToManyField(blank=True, related_name='index_nodes', to='documents.collection'),
        ),
        migrations.AddField(
            model_name='node',
            name='llm_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='service_providers.llmprovider'),
        ),
        migrations.AddField(
            model_name='node',
            name='llm_provider_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='service_providers.llmprovidermodel'),
        ),
        migrations.AddField(
            model_name='node',
            name='source_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='experiments.sourcematerial'),
        ),
        migrations.AddField(
            model_name='node',
            name='synthetic_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='experiments.syntheticvoice'),
        ),
    ]
