# Generated by Django 5.2.15 on 2026-07-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0028_pipeline_edit_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='position_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='position_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
