# Generated by Django 5.2.16 on 2026-09-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0031_remove_node_assistant_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="position_x",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="position_y",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
