# Generated by Django 5.2.16 on 2026-09-23 12:08

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("pipelines", "0034_drop_node_assistant_column"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="pipelinechathistory",
            index=models.Index(fields=["updated_at", "id"], name="pipechathist_updated_at_id_idx"),
        ),
    ]
