# Generated by Django 5.1.2 on 2024-11-29 15:04

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [TrigramExtension()]
