# Generated by Django 5.1.5 on 2025-05-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20241129_1504'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE teams_flag SET name = CONCAT('flag_', name) WHERE name NOT LIKE 'flag_%'",
            "UPDATE teams_flag SET name = SUBSTRING(name, 6) WHERE name LIKE 'flag_%'"
        ),
    ]
