# Generated by Django 4.2.7 on 2024-01-26 10:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0005_invitation_groups"),
        ("service_providers", "0008_messagingprovider"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAiAssistant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assistant_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("instructions", models.TextField()),
                (
                    "builtin_tools",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128), default=list, size=None
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(help_text="The LLM model to use.", max_length=255, verbose_name="LLM Model"),
                ),
                (
                    "llm_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="service_providers.llmprovider",
                        verbose_name="LLM Provider",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.team", verbose_name="Team"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
