# Generated by Django 4.2.7 on 2024-02-07 09:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaiassistant",
            name="builtin_tools",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), blank=True, default=list, size=None
            ),
        ),
    ]
