# Generated by Django 4.2.7 on 2024-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('assistants', '0002_alter_openaiassistant_builtin_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiassistant',
            name='files',
            field=models.ManyToManyField(blank=True, to='files.file'),
        ),
    ]
