# Generated by Django 4.2.7 on 2024-04-26 13:16
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
        ("assistants", "0003_openaiassistant_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaiassistant",
            name="temperature",
            field=models.FloatField(default=1.0, validators=[MinValueValidator(0.0), MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name="openaiassistant",
            name="top_p",
            field=models.FloatField(default=1.0, validators=[MinValueValidator(0.0), MaxValueValidator(1.0)]),
        ),
        migrations.AlterModelOptions(
            name="openaiassistant",
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="ToolResources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tool_type", models.CharField(max_length=128)),
                ("extra", models.JSONField(default=dict, blank=True)),
                (
                    "assistant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_resources",
                        to="assistants.openaiassistant",
                    ),
                ),
                ("files", models.ManyToManyField(blank=True, to="files.file")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
