# Generated by Django 4.2.7 on 2024-04-26 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
        ("assistants", "0004_openaiassistant_temperature_openaiassistant_top_p_and_more"),
    ]

    operations = []
