# Generated by Django 4.2.11 on 2024-07-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('chat', '0015_chatmessage_metadata'),
        ('assistants', '0005_migrate_assistants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadToolResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_type', models.CharField(max_length=128)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_resources', to='chat.chat')),
                ('files', models.ManyToManyField(blank=True, to='files.file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
