# Generated by Django 5.1.2 on 2024-11-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0007_openaiassistant_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiassistant',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openaiassistant',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='openaiassistant',
            name='working_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assistants.openaiassistant'),
        ),
    ]
