# Generated by Django 5.1.2 on 2024-10-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistants", "0007_openaiassistant_tools"),
        ("custom_actions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaiassistant",
            name="custom_actions",
            field=models.ManyToManyField(
                blank=True, related_name="assistants", to="custom_actions.customaction"
            ),
        ),
    ]
