# Generated by Django 5.1.2 on 2024-11-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistants", "0007_openaiassistant_tools"),
        ("custom_actions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaiassistant",
            name="custom_actions",
            field=models.ManyToManyField(
                blank=True,
                related_name="assistants",
                through="custom_actions.CustomActionOperation",
                to="custom_actions.customaction",
            ),
        ),
    ]
