# Generated by Django 5.1.2 on 2024-11-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0009_openaiassistant_is_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openaiassistant',
            name='llm_model',
        ),
    ]
