# Generated by Django 5.1.2 on 2024-12-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0010_remove_openaiassistant_llm_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiassistant',
            name='allow_code_interpreter_attachments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='openaiassistant',
            name='allow_file_search_attachments',
            field=models.BooleanField(default=True),
        ),
    ]
