# Generated by Django 5.1.2 on 2024-12-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0011_openaiassistant_allow_code_interpreter_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openaiassistant',
            name='files',
        ),
    ]
