# Generated by Django 5.1.5 on 2025-03-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_toolresources_allow_file_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiassistant',
            name='allow_file_downloads',
            field=models.BooleanField(default=True),
        ),
    ]
