# Generated by Django 5.1.5 on 2025-10-23 11:10

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0013_openaiassistant_allow_file_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolresources',
            name='extra',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=dict),
        ),
    ]
