# Generated by Django 5.1.5 on 2025-03-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0014_openaiassistant_allow_file_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolresources',
            name='allow_file_downloads',
        ),
    ]
