# Generated by Django 5.1.5 on 2025-08-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userapikey_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='read_only',
            field=models.BooleanField(default=True),
        ),
    ]
