# Generated by Django 4.2.11 on 2024-06-13 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_invitation_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotations', '0002_usercomment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('bot_response', 'Bot Response')], default='bot_response'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_system_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customtaggeditem',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('team', 'name', 'is_system_tag', 'category')},
        ),
    ]
