# Generated by Django 5.1.5 on 2025-12-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('annotations', '0008_alter_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[
                ('bot_response', 'Bot Response'),
                ('safety_layer_response', 'Safety Layer Response'),
                ('experiment_version', 'Experiment Version'),
                ('response_rating', 'Response Rating'),
                ('error', 'Error'),
                ('voice', 'Voice')
            ], default=''),
        ),
    ]
