# Generated by Django 5.2.12 on 2026-04-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0009_alter_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('bot_response', 'Bot Response'), ('safety_layer_response', 'Safety Layer Response'), ('experiment_version', 'Experiment Version'), ('response_rating', 'Response Rating'), ('error', 'Error'), ('media_type', 'Media Type'), ('evaluations', 'Evaluations')], default=''),
        ),
    ]
