# Generated by Django 5.2.16 on 2026-09-23 12:08

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("annotations", "0009_alter_tag_category"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="usercomment",
            index=models.Index(fields=["updated_at", "id"], name="usercomment_updated_at_id_idx"),
        ),
    ]
