META_EMBEDDING_ID = "embedding_id"

META_EXPERIMENT_ID = "experiment_id"

META_FILE_ID = "file_id"

META_SEARCH_SCORE = "search_score"

META_ALL = (META_EMBEDDING_ID, META_EXPERIMENT_ID, META_FILE_ID, META_SEARCH_SCORE)
