# Generated by Django 5.1.5 on 2025-10-15 13:45

import apps.utils.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0007_create_commcare_connect_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('table_type', models.CharField(choices=[('sessions', 'Sessions'), ('datasets', 'Datasets')], max_length=50)),
                ('filter_query_string', models.CharField()),
                ('is_shared', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_default_for_user', models.BooleanField(default=False)),
                ('is_default_for_team', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'table_type', 'user'], name='filters_fil_team_id_891b97_idx'), models.Index(fields=['team', 'table_type', 'is_default_for_team'], name='filters_fil_team_id_acf9b1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default_for_user', True), ('is_deleted', False)), fields=('team', 'user', 'table_type'), name='unique_default_filterset_per_user_table_type'), models.UniqueConstraint(condition=models.Q(('is_default_for_team', True), ('is_deleted', False)), fields=('team', 'table_type'), name='unique_default_filterset_per_team_table_type')],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
