# Generated by Django 5.1.15 on 2026-01-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterset',
            name='table_type',
            field=models.CharField(choices=[('sessions', 'Sessions'), ('datasets', 'Datasets'), ('all_sessions', 'All Sessions'), ('participants', 'Participants'), ('traces', 'Traces'), ('notifications', 'Notifications')], max_length=50),
        ),
    ]
