# Generated by Django 5.2.12 on 2026-04-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_alter_filterset_table_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterset',
            name='table_type',
            field=models.CharField(choices=[('sessions', 'Sessions'), ('datasets', 'Datasets'), ('all_sessions', 'All Sessions'), ('participants', 'Participants'), ('traces', 'Traces'), ('notifications', 'Notifications'), ('annotation_items', 'Annotation Items')], max_length=50),
        ),
    ]
