# Generated by Django 5.1.5 on 2025-07-17 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0018_chat_translated_languages_chatmessage_translations'),
        ('experiments', '0114_delete_trace'),
        ('teams', '0007_create_commcare_connect_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField()),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='experiments.experiment')),
                ('input_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_message_trace', to='chat.chatmessage')),
                ('output_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_message_trace', to='chat.chatmessage')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='experiments.participant')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='experiments.experimentsession')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='teams.team')),
            ],
        ),
    ]
