# Generated by Django 5.1.5 on 2025-07-16 13:40

import apps.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0114_delete_trace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('output_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField()),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='experiments.experiment')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='experiments.participant')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='experiments.experimentsession')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
