# Generated by Django 5.1.5 on 2025-08-13 08:18

import apps.utils.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_create_commcare_connect_flag'),
        ('trace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('error', 'Error')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='trace',
            name='trace_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('span_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('error', 'Error')], default='pending', max_length=32)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True)),
                ('parent_span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_spans', to='trace.span')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='trace.trace')),
            ],
            options={
                'indexes': [models.Index(fields=['trace_id'], name='trace_span_trace_i_68fd64_idx'), models.Index(fields=['parent_span_id'], name='trace_span_parent__a88487_idx'), models.Index(fields=['start_time'], name='trace_span_start_t_4ff4a0_idx'), models.Index(fields=['name'], name='trace_span_name_4ea4c7_idx')],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
