# Generated by Django 5.1.5 on 2025-08-12 14:49

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0008_alter_tag_category'),
        ('trace', '0002_trace_status_trace_trace_id_span'),
    ]

    operations = [
        migrations.AddField(
            model_name='span',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='annotations.CustomTaggedItem', to='annotations.Tag', verbose_name='Tags'),
        ),
    ]
