# Generated by Django 5.1.5 on 2025-09-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace', '0003_span_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('error', 'Error')], db_index=True, default='pending', max_length=32),
        ),
    ]
