# Generated by Django 5.1.5 on 2025-09-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace', '0003_span_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='participant_data',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of participant data at the time of the trace'),
        ),
        migrations.AddField(
            model_name='trace',
            name='session_state',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of session state at the time of the trace'),
        ),
        migrations.AlterField(
            model_name='trace',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('error', 'Error')], db_index=True, default='pending', max_length=32),
        ),
    ]
