# Generated by Django 5.1.5 on 2025-09-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace', '0004_alter_trace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='participant_data',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of participant data at the time of the trace'),
        ),
        migrations.AddField(
            model_name='trace',
            name='session_state',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of session state at the time of the trace'),
        ),
    ]
