# Generated by Django 5.1.5 on 2025-10-23 11:10

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trace', '0005_trace_experiment_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='span',
            name='input',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='span',
            name='metadata',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='span',
            name='output',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='trace',
            name='participant_data',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=dict, help_text='Snapshot of participant data at the time of the trace'),
        ),
        migrations.AlterField(
            model_name='trace',
            name='session_state',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=dict, help_text='Snapshot of session state at the time of the trace'),
        ),
    ]
