# Generated by Django 5.1.5 on 2026-01-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace', '0006_alter_span_input_alter_span_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='error',
            field=models.TextField(blank=True, help_text='Error message if the trace failed'),
        ),
    ]
