# Generated by Django 5.1.5 on 2025-11-24 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_move_models_from_experiments'),
        ('trace', '0006_alter_span_input_alter_span_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='participants.participant'),
        ),
    ]
