# Generated by Django 5.2.11 on 2026-03-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_alter_chatattachment_unique_together'),
        ('experiments', '0130_remove_experiment_llm_provider_and_more'),
        ('teams', '0008_drop_unused_waffle_tables'),
        ('trace', '0008_delete_span'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trace',
            index=models.Index(fields=['session', 'timestamp'], name='trace_trace_session_f3ae96_idx'),
        ),
    ]
