# Generated by Django 5.2.12 on 2026-03-09 13:52

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trace', '0008_delete_span'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='participant_data_diff',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=list, help_text='Diff of participant data changes during this trace'),
        ),
    ]
