# Generated by Django 5.2.12 on 2026-03-26 09:13

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trace', '0009_trace_participant_data_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='trace_metadata',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=dict, help_text='Metadata from trace providers (e.g. Langfuse trace_id, trace_url)'),
        ),
    ]
