# Generated by Django 5.2.12 on 2026-04-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace', '0010_trace_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='n_toolcalls',
            field=models.IntegerField(blank=True, help_text='Number of tool invocations across all turns', null=True),
        ),
        migrations.AddField(
            model_name='trace',
            name='n_total_tokens',
            field=models.IntegerField(blank=True, help_text='Total tokens (prompt + completion) consumed', null=True),
        ),
        migrations.AddField(
            model_name='trace',
            name='n_prompt_tokens',
            field=models.IntegerField(blank=True, help_text='Total input/prompt tokens consumed', null=True),
        ),
        migrations.AddField(
            model_name='trace',
            name='n_completion_tokens',
            field=models.IntegerField(blank=True, help_text='Total output/completion tokens consumed', null=True),
        ),
        migrations.AddField(
            model_name='trace',
            name='n_turns',
            field=models.IntegerField(blank=True, help_text='Number of LLM calls during pipeline execution', null=True),
        ),
        migrations.AddField(
            model_name='trace',
            name='time_to_first_token',
            field=models.IntegerField(blank=True, help_text='Time from pipeline start to first LLM token in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='trace',
            name='time_to_last_token',
            field=models.IntegerField(blank=True, help_text='Time from pipeline start to last LLM token in milliseconds', null=True),
        ),
    ]
