# Generated by Django 5.2.13 on 2026-06-24 09:00

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('chat', '0025_chatmessage_chatmessage_created_at_idx'),
        ('experiments', '0145_experimentsession_expsession_created_at_idx_and_more'),
        ('teams', '0012_team_metadata'),
        ('trace', '0012_trace_indexes'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='trace',
            index=models.Index(fields=['timestamp'], name='trace_timestamp_idx'),
        ),
    ]
