# Generated by Django 5.2.15 on 2026-07-31 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trace", "0014_remove_stale_span_contenttype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trace",
            name="n_completion_tokens",
        ),
        migrations.RemoveField(
            model_name="trace",
            name="n_prompt_tokens",
        ),
        migrations.RemoveField(
            model_name="trace",
            name="n_total_tokens",
        ),
    ]
