# Generated by Django 5.1.5 on 2025-11-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomMigration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for the migration",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when migration was applied",
                    ),
                ),
            ],
            options={
                "db_table": "custom_migrations",
                "ordering": ["-applied_at"],
            },
        ),
    ]
