# See https://www.twilio.com/docs/messaging/guides/accepted-mime-types
TWILIO = [
    # Images
    "image/jpeg",
    "image/jpg",
    "image/gif",
    "image/png",
    "image/heic",
    "image/heif",
    "image/tiff",
    "image/bmp",
    "image/webp",
    # Videos
    "video/mpeg4",
    "video/mp4",
    "video/mpeg",
    "video/webm",
    "video/quicktime",
    "video/3gpp",
    "video/3gpp2",
    "video/3gpp-tt",
    "video/H261",
    "video/H263",
    "video/H263-1998",
    "video/H263-2000",
    "video/H264",
    "video/H265",
    # Audio
    "audio/ogg",
    "audio/mpeg",
    "audio/mp4",
    "audio/mp3",
    "audio/3gpp",
    "audio/3gpp2",
    "audio/basic",
    "audio/L24",
    "audio/vnd.rn-realaudio",
    "audio/vnd.wave",
    "audio/ac3",
    "audio/webm",
    "audio/amr-nb",
    "audio/amr",
    # Text
    "text/vcard",
    "text/x-vcard",
    "text/directory",
    "text/csv",
    "text/richtext",
    "text/rtf",
    "text/calendar",
    # Application
    "application/pdf",
    "application/vnd.apple.pkpass",
    "application/vcard",
    "application/msword",
    "application/vnd.ms-excel",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
]
