from django.conf import settings
from django_tables2 import columns, tables


def make_table(provider_type, model, fields=("type", "name")):
    meta_attrs = {
        "model": model,
        "fields": fields,
        "row_attrs": settings.DJANGO_TABLES2_ROW_ATTRS,
        "orderable": False,
    }
    Meta = type("Meta", (object,), meta_attrs)

    class_name = model.__name__ + "AutogeneratedTable"
    table_class_attrs = {
        "actions": columns.TemplateColumn(
            template_name="service_providers/actions_column.html",
            extra_context={
                "edit_url_name": "service_providers:edit",
                "delete_url_name": "service_providers:delete",
                "provider_type": provider_type,
            },
        ),
        "Meta": Meta,
    }
    return type(tables.Table)(class_name, (tables.Table,), table_class_attrs)
