# Generated by Django 4.2.7 on 2023-12-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_analysis_config"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysisrun",
            old_name="resources",
            new_name="output_resources",
        ),
        migrations.AlterField(
            model_name="analysisrun",
            name="output_resources",
            field=models.ManyToManyField(related_name="+", to="analysis.resource"),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="input_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="analysis.resource",
            ),
        ),
    ]
