# Generated by Django 4.2.7 on 2023-12-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0003_rename_resources_analysisrun_output_resources_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="content_type",
            field=models.CharField(blank=True, null=True),
        ),
    ]
