# Generated by Django 4.2.7 on 2023-12-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_resource_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("csv", "CSV"),
                    ("json", "JSON"),
                    ("jsonl", "JSON Lines"),
                    ("xml", "XML"),
                    ("xlsx", "XLSX"),
                    ("image", "Image"),
                    ("unknown", "Unknown"),
                ],
                max_length=128,
            ),
        ),
    ]
