# Generated by Django 4.2.7 on 2023-12-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0005_alter_resource_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("error", "Error"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="rungroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("error", "Error"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=128,
            ),
        ),
    ]
