# Generated by Django 4.2.7 on 2023-12-20 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0008_rungroup_approved_rungroup_created_by_rungroup_notes_and_more"),
    ]

    operations = []
