# Generated by Django 4.2.7 on 2024-03-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0009_migrate_step_params"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="llm_model",
            field=models.CharField(
                help_text="The LLM model to use.",
                max_length=255,
                verbose_name="LLM Model",
            ),
        ),
    ]
