# Generated by Django 5.1.5 on 2025-04-29 16:40

import apps.utils.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0110_alter_participantdata_data'),
        ('service_providers', '0026_add_google_gemini_models'),
        ('teams', '0007_create_commcare_connect_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('query_file', models.FileField(upload_to='analysis_queries/')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='analysis_results/')),
                ('error_message', models.TextField(blank=True)),
                ('job_id', models.CharField(blank=True, max_length=255)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_analyses', to='experiments.experiment')),
                ('llm_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_providers.llmprovider', verbose_name='LLM Provider')),
                ('llm_provider_model', models.ForeignKey(blank=True, help_text='The LLM model to use', null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_providers.llmprovidermodel', verbose_name='LLM Model')),
                ('sessions', models.ManyToManyField(related_name='analyses', to='experiments.experimentsession')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
        migrations.CreateModel(
            name='AnalysisQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('prompt', models.TextField()),
                ('output_format', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='analysis.transcriptanalysis')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
