# Generated by Django 5.1.5 on 2025-05-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptanalysis',
            name='query_file',
            field=models.FileField(blank=True, null=True, upload_to='analysis_queries/'),
        ),
    ]
