# Generated by Django 5.2.13 on 2026-06-12 10:23

import apps.utils.fields
import apps.utils.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0142_remove_experiment_use_processor_bot_voice'),
        ('teams', '0010_create_flag_ai_cost_monitoring'),
        ('trace', '0012_trace_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=128)),
                ('service_kind', models.CharField(choices=[('llm_input', 'Llm Input'), ('llm_output', 'Llm Output'), ('llm_cached_input', 'Llm Cached Input'), ('llm_cache_write', 'Llm Cache Write')], max_length=32)),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('manual', 'Manual'), ('import', 'Import')], default='seed', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('service_kind', models.CharField(choices=[('llm_input', 'Llm Input'), ('llm_output', 'Llm Output'), ('llm_cached_input', 'Llm Cached Input'), ('llm_cache_write', 'Llm Cache Write')], max_length=32)),
                ('provider_type', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=128)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=14, null=True)),
                ('cost', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('confidence', models.CharField(choices=[('exact', 'Exact'), ('estimated', 'Estimated'), ('unknown', 'Unknown')], default='exact', max_length=16)),
                ('extra', apps.utils.fields.SanitizedJSONField(blank=True, default=dict)),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiments.experiment')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiments.participant')),
                ('pricing_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cost_tracking.pricingrule')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiments.experimentsession')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('trace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trace.trace')),
            ],
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['team', 'provider_type', 'model_name', 'service_kind', 'effective_from'], name='cost_tracki_team_id_b84501_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('team', 'provider_type', 'model_name', 'service_kind'), name='cost_tracking_unique_active_pricing_rule', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['team', 'timestamp'], name='cost_tracki_team_id_70ddb9_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['team', 'experiment', 'timestamp'], name='cost_tracki_team_id_781e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['team', 'session', 'timestamp'], name='cost_tracki_team_id_80d03b_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['team', 'model_name', 'timestamp'], name='cost_tracki_team_id_82ee7f_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['team', 'confidence', 'timestamp'], name='cost_tracki_team_id_35769e_idx'),
        ),
    ]
