# Generated by Django 5.2.13 on 2026-06-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_tracking', '0002_seed_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='service_kind',
            field=models.CharField(choices=[('llm_input', 'Llm Input'), ('llm_output', 'Llm Output'), ('llm_cached_input', 'Llm Cached Input'), ('llm_cache_write', 'Llm Cache Write')], max_length=32),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='service_kind',
            field=models.CharField(choices=[('llm_input', 'Llm Input'), ('llm_output', 'Llm Output'), ('llm_cached_input', 'Llm Cached Input'), ('llm_cache_write', 'Llm Cache Write')], max_length=32),
        ),
    ]
