# Generated by Django 5.2.13 on 2026-06-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_tracking', '0003_drop_llm_reasoning_service_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingrule',
            name='updated_at',
        ),
    ]
