# Generated by Django 5.2.13 on 2026-06-11 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_tracking', '0004_remove_pricingrule_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagerecord',
            name='pricing_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cost_tracking.pricingrule'),
        ),
    ]
