# Generated by Django 4.2 on 2023-10-24 12:01

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


def copy_llm_providers(apps, schema_editor):
    LlmProviderOld = apps.get_model("llm_providers", "LlmProvider")
    LlmProviderNew = apps.get_model("service_providers", "LlmProvider")

    for provider in LlmProviderOld.objects.all():
        LlmProviderNew.objects.create(
            team_id=provider.team_id,
            name=provider.name,
            type=provider.type,
            config=provider.config,
            old_id=provider.id,
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("service_providers", "0001_initial"),
        ("experiments", "0047_bootstrap_llm_provider"),
    ]

    operations = [
        migrations.RunPython(copy_llm_providers)
    ]
