# Generated by Django 4.2 on 2023-10-24 12:01

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("service_providers", "0001_initial"),
        ("experiments", "0047_bootstrap_llm_provider"),
    ]

    operations = [
        # operations removed when removing the model
    ]
