# Generated by Django 4.2 on 2023-10-26 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service_providers", "0003_migrate_experiments_to_new_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llmprovider",
            name="old_id",
        ),
    ]
