# Generated by Django 4.2 on 2023-11-02 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_flag"),
        ("service_providers", "0005_voiceprovider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmprovider",
            name="team",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="teams.team"),
        ),
    ]
