# Generated by Django 4.2 on 2023-11-08 07:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_providers", "0006_alter_llmprovider_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmprovider",
            name="llm_models",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                default=list,
                size=None,
                verbose_name="LLM Models",
                help_text="The models that will be available for use. Separate multiple models with a comma.",
            ),
        ),
    ]
