# Generated by Django 4.2.7 on 2024-02-06 12:00

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0005_invitation_groups"),
        ("service_providers", "0009_alter_llmprovider_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagingprovider",
            name="type",
            field=models.CharField(choices=[("twilio", "Twilio"), ("turnio", "Turn.io")], max_length=255),
        ),
        migrations.CreateModel(
            name="AuthProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(choices=[("commcare", "CommCare")], max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("config", django_cryptography.fields.encrypt(models.JSONField(default=dict))),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.team", verbose_name="Team"
                    ),
                ),
            ],
            options={
                "ordering": ("type", "name"),
            },
        ),
    ]
