# Generated by Django 4.2.7 on 2024-02-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_providers", "0010_alter_messagingprovider_type_authprovider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagingprovider",
            name="type",
            field=models.CharField(choices=[("twilio", "Twilio"), ("turnio", "Turn.io")], max_length=255),
        ),
    ]
