# Generated by Django 4.2.7 on 2024-04-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0011_alter_messagingprovider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceprovider',
            name='type',
            field=models.CharField(choices=[('aws', 'AWS Polly'), ('azure', 'Azure Text to Speech'), ('openai', 'OpenAI Text to Speech')], max_length=255),
        ),
    ]
