# Generated by Django 4.2.7 on 2024-04-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('service_providers', '0012_alter_voiceprovider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceprovider',
            name='files',
            field=models.ManyToManyField(blank=True, to='files.file'),
        ),
        migrations.AlterField(
            model_name='voiceprovider',
            name='type',
            field=models.CharField(choices=[('aws', 'AWS Polly'), ('azure', 'Azure Text to Speech'), ('openai', 'OpenAI Text to Speech'), ('openaivoiceengine', 'OpenAI VE Text to Speech')], max_length=255),
        ),
    ]
