# Generated by Django 4.2.7 on 2024-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0012_alter_voiceprovider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceprovider',
            name='type',
            field=models.CharField(choices=[('aws', 'AWS Polly'), ('azure', 'Azure Text to Speech'), ('openai', 'OpenAI Text to Speech'), ('openaivoiceengine', 'OpenAI Voice Engine Text to Speech')], max_length=255),
        ),
    ]
