# Generated by Django 4.2.11 on 2024-06-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_providers", "0013_alter_voiceprovider_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagingprovider",
            name="type",
            field=models.CharField(
                choices=[
                    ("twilio", "Twilio"),
                    ("turnio", "Turn.io"),
                    ("slack", "Slack"),
                ],
                max_length=255,
            ),
        ),
    ]
