# Generated by Django 4.2.7 on 2024-04-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0013_voiceprovider_files_alter_voiceprovider_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceprovider',
            name='files',
        ),
    ]
