# Generated by Django 4.2.14 on 2024-07-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0014_alter_messagingprovider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingprovider',
            name='type',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('turnio', 'Turn.io'), ('sureadhere', 'SureAdhere'), ('slack', 'Slack')], max_length=255),
        ),
    ]
