# Generated by Django 4.2.15 on 2024-08-15 08:47

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0006_remove_invitation_role_remove_membership_role"),
        ("service_providers", "0015_alter_messagingprovider_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("langfuse", "Langfuse")], max_length=255
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "config",
                    django_cryptography.fields.encrypt(models.JSONField(default=dict)),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "ordering": ("type", "name"),
            },
        ),
    ]
