# Generated by Django 5.1 on 2024-09-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_providers", "0016_traceprovider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traceprovider",
            name="type",
            field=models.CharField(
                choices=[("langfuse", "Langfuse"), ("langsmith", "LangSmith")],
                max_length=255,
            ),
        ),
    ]
