# Generated by Django 5.1 on 2024-10-24 10:35

import apps.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0017_alter_traceprovider_type'),
        ('teams', '0006_remove_invitation_role_remove_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic')], max_length=255)),
                ('name', models.CharField(help_text="The name of the model. e.g. 'gpt-4o-mini' or 'claude-3-5-sonnet-20240620'", max_length=128)),
                ('max_token_limit', models.PositiveIntegerField(default=8192, help_text='When the message history for a session exceeds this limit (in tokens), it will be compressed. If 0, compression will be disabled which may result in errors or high LLM costs.')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'name', 'type', 'max_token_limit'), name='unique_team_name_type_max_token_limit')],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
