# Generated by Django 5.1.2 on 2024-10-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_providers", "0017_alter_traceprovider_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authprovider",
            name="type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("api_key", "API Key"),
                    ("bearer", "Bearer Auth"),
                    ("commcare", "CommCare"),
                ],
                max_length=255,
            ),
        ),
    ]
