# Generated by Django 5.1.2 on 2024-11-11 11:13
import logging

from collections import namedtuple
from django.db import migrations
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0019_llmprovidermodel'),
        ('pipelines', '0008_pipelinechatmessages_node_id_and_more'),
    ]

    operations = [
        # operations removed
    ]
