# Generated by Django 5.1.2 on 2024-11-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0020_auto_20241111_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmprovider',
            name='llm_models',
        ),
    ]
