# Generated by Django 5.1.2 on 2025-02-18 11:13
import logging
from django.db import migrations

logger = logging.getLogger(__name__)


def _add_llm_provider_models(apps, schema_editor):
    LlmProviderModel = apps.get_model("service_providers", "LlmProviderModel")

    try:
        LlmProviderModel.objects.create(
            type='deepseek',
            name='deepseek-v3',
            max_token_limit=128000,
        )

        LlmProviderModel.objects.create(
            type='deepseek',
            name='deepseek-r1',
            max_token_limit=128000
        )
    except Exception as e:
        logger.error(f"Error while adding new rows to LlmProviderModel: {e}")
        raise


class Migration(migrations.Migration):
    dependencies = [
        ('service_providers', '0024_add_deepseek_models'),
    ]

    operations = [
        migrations.RunPython(_add_llm_provider_models),
    ]
