# Generated by Django 5.1.5 on 2025-05-28 18:38

from django.db import migrations, models


def confirm_no_langsmith_providers(apps, schema_editor):
    TraceProvider = apps.get_model('service_providers', 'TraceProvider')
    # Check if there are any providers of type 'langsmith'
    if TraceProvider.objects.filter(type='langsmith').exists():
        raise ValueError(
            "There are still providers of type 'langsmith'."
            " Please remove them before applying this migration."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0025_alter_llmprovider_type_alter_llmprovidermodel_type'),
    ]

    operations = [
        migrations.RunPython(
            confirm_no_langsmith_providers,
            migrations.RunPython.noop,  # No reverse migration needed
        ),
        migrations.AlterField(
            model_name='traceprovider',
            name='type',
            field=models.CharField(choices=[('langfuse', 'Langfuse')], max_length=255),
        ),
    ]
