# Generated by Django 5.1.5 on 2025-05-30 08:24

import apps.utils.models
import django.db.models.deletion
from django.db import migrations, models
import logging


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0027_alter_traceprovider_type'),
        ('teams', '0007_create_commcare_connect_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('google', 'Google Gemini')], max_length=255)),
                ('name', models.CharField(help_text="The name of the model. e.g. 'text-embedding-3-small'", max_length=128)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'name', 'type'), name='unique_team_name_type')],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
