# Generated by Django 5.1.5 on 2025-02-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0025_alter_llmprovider_type_alter_llmprovidermodel_type'),
        ('service_providers', '0027_alter_llmprovider_type_alter_llmprovidermodel_type'),
    ]

    operations = [
    ]
