# Generated by Django 5.1.5 on 2025-05-29 07:29

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def update_embedding_models(apps, schema_editor):
    from apps.service_providers.embedding_service.default_models import _update_embedding_provider_models
    EmbeddingProviderModel = apps.get_model("service_providers", "EmbeddingProviderModel")
    try:
        _update_embedding_provider_models(EmbeddingProviderModel)
    except Exception as e:
        logger.error(f"Error updating EmbeddingProviderModel: {e}")
        raise

class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0027_embeddingprovider_embeddingprovidermodel'),
    ]

    operations = [
        migrations.RunPython(update_embedding_models, reverse_code=migrations.RunPython.noop),
    ]
