# Generated by Django 5.1.2 on 2025-06-18 11:13
import logging
from django.db import migrations

logger = logging.getLogger(__name__)

def add_o3_model(apps, schema_editor):
    from apps.service_providers.llm_service.default_models import _update_llm_provider_models
    LlmProviderModel = apps.get_model("service_providers", "LlmProviderModel")
    try:
        _update_llm_provider_models(LlmProviderModel)
    except Exception as e:
        logger.error(f"Error updating LlmProviderModel: {e}")
        raise

class Migration(migrations.Migration):
    dependencies = [
        ('service_providers', '0028_embeddingprovidermodel'),
    ]
