# Generated by Django 5.1.2 on 2025-06-18 11:13
import logging
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('service_providers', '0028_embeddingprovidermodel'),
    ]
