# Generated by Django 5.1.5 on 2025-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0029_add_o3_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovidermodel',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
