# Generated by Django 5.1.5 on 2025-07-29 12:17

from django.db import migrations

from apps.service_providers.migration_utils import embedding_model_migration


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0031_deprecate_claude_opus_3'),
    ]

    operations = [
        embedding_model_migration()
    ]
