# Generated by Django 5.1.5 on 2025-07-29 12:17

from django.db import migrations
import logging


def update_embedding_models(apps, schema_editor):
    from apps.service_providers.llm_service.default_models import _update_embedding_provider_models
    EmbeddingProviderModel = apps.get_model("service_providers", "EmbeddingProviderModel")
    try:
        _update_embedding_provider_models(EmbeddingProviderModel)
    except Exception as e:
        logging.error(f"Error updating EmbeddingProviderModel: {e}")
        raise

class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0031_deprecate_claude_opus_3'),
    ]

    operations = [
        migrations.RunPython(update_embedding_models, reverse_code=migrations.RunPython.noop),
    ]
