# Generated by Django 5.1.5 on 2025-11-05 14:01

from django.db import migrations
import logging


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0033_fix_deepseek_typo'),
    ]

    operations = []
