# Generated by Django 5.1.5 on 2025-11-05 14:01

from django.db import migrations
import logging

logger = logging.getLogger(__name__)

def _update_openai_models(apps, schema_editor):
    from apps.service_providers.llm_service.default_models import _update_llm_provider_models
    LlmProviderModel = apps.get_model("service_providers", "LlmProviderModel")
    try:
        _update_llm_provider_models(LlmProviderModel)
    except Exception as e:
        logger.error(f"Error updating LlmProviderModel: {e}")
        raise

class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0033_fix_deepseek_typo'),
    ]

    operations = [
        migrations.RunPython(_update_openai_models, reverse_code=migrations.RunPython.noop),
    ]
