# Generated by Django 5.1.5 on 2025-11-10 13:42

from django.db import migrations, models
from apps.service_providers.llm_service.default_models import LLM_MODEL_PARAMETERS

def _populate_temperature_params(apps, schema_editor):
    """
    This is data migration that prepares the addition of the temperature parameter to the LLM model parameters.

    For all Nodes using LLM models that support temperature parameter, we need to populate the `llm_model_parameters`
    param in the node param with the existing temperature value.
    """
    models_supporting_temperature = []
    for model, params in LLM_MODEL_PARAMETERS.items():
        if hasattr(params, 'llm_temperature'):
            models_supporting_temperature.append(model)

    Node = apps.get_model('pipelines', 'Node')
    LlmProviderModel = apps.get_model('service_providers', 'LlmProviderModel')

    supported_model_ids = LlmProviderModel.objects.filter(name__in=models_supporting_temperature).values_list('id', flat=True)

    nodes_to_save = []
    for idx, node in enumerate(Node.objects.filter(params__llm_provider_model_id__in=supported_model_ids).iterator()):
        params = node.params
        llm_model_params = params.get("llm_model_params", {})
        
        # llm_temperature should exist for all these models, but default to 0.7 just in case
        llm_model_params["temperature"] = params.get("llm_temperature", 0.7)
        params["llm_model_params"] = llm_model_params
        node.params = params
        nodes_to_save.append(node)
        if len(idx) % 100 == 0:
            Node.objects.bulk_update(nodes_to_save, ['params'])
            nodes_to_save = []
    
    
    # Final save for any remaining nodes
    Node.objects.bulk_update(nodes_to_save, ['params'])

class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0034_update_openai_models'),
    ]

    operations = [
        migrations.RunPython(_populate_temperature_params, reverse_code=migrations.RunPython.noop),
    ]
