# Generated by Django 5.1.5 on 2025-11-10 13:42

from django.db import migrations
from apps.service_providers import migration_utils

def _populate_temperature_params(apps, schema_editor):
    """
    This is data migration that prepares the addition of the temperature parameter to the LLM model parameters.
    """
    Node = apps.get_model('pipelines', 'Node')
    migration_utils.populate_temperature_params(Node)


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0035_update_openai_models'),
    ]

    operations = [
        migrations.RunPython(_populate_temperature_params, reverse_code=migrations.RunPython.noop),
    ]
