# Generated by Django 5.1.5 on 2025-12-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0036_populate_temperature_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingprovidermodel',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('google', 'Google Gemini'), ('google_vertex_ai', 'Google Vertex AI')], max_length=255),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('google', 'Google Gemini'), ('google_vertex_ai', 'Google Vertex AI')], max_length=255),
        ),
        migrations.AlterField(
            model_name='llmprovidermodel',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('google', 'Google Gemini'), ('google_vertex_ai', 'Google Vertex AI')], max_length=255),
        ),
    ]
