# Generated by Django 5.1.5 on 2025-12-04 13:00

from django.db import migrations, models
from apps.service_providers.migration_utils import llm_model_migration

class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0036_populate_temperature_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingprovidermodel',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('google', 'Google Gemini'), ('google-vertex-ai', 'Google Vertex AI')], max_length=255),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('google', 'Google Gemini'), ('google-vertex-ai', 'Google Vertex AI')], max_length=255),
        ),
        migrations.AlterField(
            model_name='llmprovidermodel',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('google', 'Google Gemini'), ('google-vertex-ai', 'Google Vertex AI')], max_length=255),
        ),
        llm_model_migration()
    ]
