# Generated by Django 5.1.5 on 2025-12-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0037_alter_embeddingprovidermodel_type_and_more'),
    ]

    operations = []
