# Generated by Django 5.1.5 on 2025-12-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0038_add_gpt_5_1_model'),
    ]

    operations = []
