# Generated by Django 5.1.5 on 2025-12-12 14:03

from django.db import migrations

from apps.service_providers.migration_utils import llm_model_migration


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0038_add_gpt_5_1_model'),
    ]

    operations = [
        llm_model_migration(),
    ]
