# Generated by Django 5.1.5 on 2026-02-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0040_remove_shutdown_models'),
    ]

    operations = []
