# Generated by Django 5.1.5 on 2026-02-06 11:00

from django.db import migrations

from apps.service_providers.migration_utils import llm_model_migration


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0040_remove_shutdown_models'),
    ]

    operations = [
        llm_model_migration(),
    ]
