# Generated by Django 5.1.5 on 2026-02-19 06:44

from django.db import migrations

from apps.service_providers.migration_utils import llm_model_migration


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0041_add_claude_opus_4_6'),
    ]

    operations = [
        llm_model_migration(),
    ]
