# Generated by Django 5.1.5 on 2026-02-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0041_add_claude_opus_4_6'),
    ]

    operations = []
