# Generated by Django 5.2.11 on 2026-03-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0043_alter_messagingprovider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingprovider',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
