# Generated by Django 5.2.11 on 2026-03-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0043_migrate_gemini_3_pro_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagingprovider',
            name='type',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('turnio', 'Turn.io'), ('sureadhere', 'SureAdhere'), ('slack', 'Slack'), ('meta_cloud_api', 'Meta Cloud API (WhatsApp)')], max_length=255),
        ),
        migrations.AddField(
            model_name='messagingprovider',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
