# Generated by Django 5.2.12 on 2026-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0044_update_openai_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceprovider',
            name='type',
            field=models.CharField(choices=[('aws', 'AWS Polly'), ('azure', 'Azure Text to Speech'), ('openai', 'OpenAI Text to Speech'), ('openaivoiceengine', 'OpenAI Voice Engine Text to Speech'), ('openaicustomvoice', 'OpenAI Custom Voice')], max_length=255),
        ),
    ]
