# Generated by Django 5.2.12 on 2026-03-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0045_alter_messagingprovider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceprovider',
            name='type',
            field=models.CharField(choices=[('aws', 'AWS Polly'), ('azure', 'Azure Text to Speech'), ('openai', 'OpenAI Text to Speech'), ('openaivoiceengine', 'OpenAI Voice Engine Text to Speech'), ('elevenlabs', 'ElevenLabs')], max_length=255),
        ),
    ]
