# Generated by Django 5.2.12 on 2026-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0049_deprecate_openai_gpt41nano_gpt35turbo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceprovider',
            name='type',
            field=models.CharField(choices=[('aws', 'AWS Polly'), ('azure', 'Azure Text to Speech'), ('openai', 'OpenAI Text to Speech'), ('openaivoiceengine', 'OpenAI Voice Engine Text to Speech'), ('elevenlabs', 'ElevenLabs'), ('intron', 'Intron')], max_length=255),
        ),
    ]
