# Generated by Django 5.2.12 on 2026-04-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0050_alter_voiceprovider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingprovidermodel',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('google', 'Google Gemini'), ('google_vertex_ai', 'Google Vertex AI'), ('voyage', 'Voyage AI')], max_length=255),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('google', 'Google Gemini'), ('google_vertex_ai', 'Google Vertex AI'), ('voyage', 'Voyage AI')], max_length=255),
        ),
        migrations.AlterField(
            model_name='llmprovidermodel',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('google', 'Google Gemini'), ('google_vertex_ai', 'Google Vertex AI'), ('voyage', 'Voyage AI')], max_length=255),
        ),
    ]
