# Generated by Django 5.2.13 on 2026-07-08 09:09

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0059_delete_claude_sonnet_4_20250514'),
    ]

    operations = [
        migrations.AddField(
            model_name='authprovider',
            name='_auth_data',
            field=django_cryptography.fields.encrypt(models.JSONField(default=dict)),
        ),
        migrations.AlterField(
            model_name='authprovider',
            name='type',
            field=models.CharField(choices=[('basic', 'Basic'), ('api_key', 'API Key'), ('bearer', 'Bearer Auth'), ('commcare', 'CommCare'), ('oauth_client_credentials', 'OAuth (Client Credentials)')], max_length=255),
        ),
    ]
