# Generated by Django 5.2.13 on 2026-07-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0060_authprovider__auth_data_alter_authprovider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingprovidermodel',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('minimax', 'MiniMax'), ('google', 'Google Gemini'), ('google_vertex_ai', 'Google Vertex AI'), ('voyage', 'Voyage AI')], max_length=255),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('minimax', 'MiniMax'), ('google', 'Google Gemini'), ('google_vertex_ai', 'Google Vertex AI'), ('voyage', 'Voyage AI')], max_length=255),
        ),
        migrations.AlterField(
            model_name='llmprovidermodel',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('minimax', 'MiniMax'), ('google', 'Google Gemini'), ('google_vertex_ai', 'Google Vertex AI'), ('voyage', 'Voyage AI')], max_length=255),
        ),
    ]
