# Generated by Django 5.2.13 on 2026-07-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0060_authprovider__auth_data_alter_authprovider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceprovider',
            name='type',
            field=models.CharField(choices=[('aws', 'AWS Polly'), ('azure', 'Azure Text to Speech'), ('openai', 'OpenAI Text to Speech'), ('openaivoiceengine', 'OpenAI Voice Engine Text to Speech'), ('elevenlabs', 'ElevenLabs'), ('intron', 'Intron'), ('minimax', 'MiniMax')], max_length=255),
        ),
    ]
