# Generated by Django 5.2.13 on 2026-07-13 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service_providers", "0061_add_gpt_5_6_models"),
        # Retained so the graph stays stable for environments that already applied this.
        ("cost_tracking", "0001_initial"),
    ]

    operations = [
        # load_pricing_data() moved to 0078_add_gemini_3_8_flash so it runs only once per deploy
        # (the newest migration loads the whole seed file).
    ]
