# Generated by Django 5.2.13 on 2026-07-13 08:03

from django.db import migrations

from apps.cost_tracking.migration_utils import load_pricing_data


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0061_add_gpt_5_6_models'),
        ('cost_tracking', '0001_initial'),
    ]

    operations = [
        load_pricing_data(),
    ]
