# Generated by Django 5.2.15 on 2026-07-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0067_add_claude_opus_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceprovider',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-side details fetched from the tracing service (e.g. Langfuse project and organization). Populated on save; unencrypted so usage can be aggregated by project/organization.'),
        ),
    ]
