# Generated by Django 5.2.16 on 2026-08-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0074_add_deepseek_v4_flash_vision_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingprovidermodel',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('minimax', 'MiniMax'), ('litellm', 'LiteLLM'), ('google', 'Google Gemini'), ('google_vertex_ai', 'Google Vertex AI'), ('voyage', 'Voyage AI')], max_length=255),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('minimax', 'MiniMax'), ('litellm', 'LiteLLM'), ('google', 'Google Gemini'), ('google_vertex_ai', 'Google Vertex AI'), ('voyage', 'Voyage AI')], max_length=255),
        ),
        migrations.AlterField(
            model_name='llmprovidermodel',
            name='type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('perplexity', 'Perplexity'), ('deepseek', 'DeepSeek'), ('minimax', 'MiniMax'), ('litellm', 'LiteLLM'), ('google', 'Google Gemini'), ('google_vertex_ai', 'Google Vertex AI'), ('voyage', 'Voyage AI')], max_length=255),
        ),
    ]
