# Generated by Django 5.2.16 on 2026-09-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0075_alter_embeddingprovidermodel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
