# Generated by Django 5.2.16 on 2026-09-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_providers", "0077_deprecate_gpt5_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmprovider",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
