# Generated by Django 5.2.16 on 2026-09-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0086_auto_model_sync_20260923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authprovider',
            name='type',
            field=models.CharField(choices=[('basic', 'Basic'), ('api_key', 'API Key'), ('bearer', 'Bearer Auth'), ('commcare', 'CommCare'), ('oauth_client_credentials', 'OAuth (Client Credentials)'), ('oauth_authorization_code', 'OAuth (Authorization Code)')], max_length=255),
        ),
    ]
