# Generated by Django 5.2.17 on 2026-10-07 13:30

import apps.utils.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0029_updated_at_id_indexes'),
        ('experiments', '0152_updated_at_id_indexes'),
        ('teams', '0019_team_exportable_experiments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeniedParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('code_node', 'Code node')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('chat_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.chatmessage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='experiments.experiment')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denials', to='experiments.participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'participant'), name='unique_denied_participant_per_team')],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
