# Generated by Django 5.2.13 on 2026-05-20 10:47

import apps.utils.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('evaluations', '0015_auto_populate_schema'),
        ('human_annotations', '0004_backfill_authoritative'),
        ('teams', '0009_merge_pipeline_admin_into_experiment_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('numeric', 'Numeric'), ('categorical', 'Categorical'), ('boolean', 'Boolean')], max_length=20)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_string', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('llm_judge', 'LLM judge'), ('programmatic', 'Programmatic'), ('human_review', 'Human review'), ('user_feedback', 'User feedback'), ('system', 'System')], max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to=settings.AUTH_USER_MODEL)),
                ('automated_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluationresult')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='human_annotations.annotation')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'indexes': [models.Index(fields=['target_content_type', 'target_object_id', 'name', 'source'], name='assessments_target__9cccb2_idx'), models.Index(fields=['created_at'], name='assessments_created_e6970b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('automated_result__isnull', False)), fields=('automated_result', 'name'), name='score_unique_per_automated_result_field'), models.UniqueConstraint(condition=models.Q(('review__isnull', False)), fields=('review', 'name'), name='score_unique_per_review_field'), models.CheckConstraint(condition=models.Q(('value_numeric__isnull', False), ('value_string__isnull', False), _connector='OR'), name='score_value_present')],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
