# Generated by Django 5.2.16 on 2026-09-23 12:08

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="score",
            index=models.Index(fields=["updated_at", "id"], name="score_updated_at_id_idx"),
        ),
    ]
