# Generated by Django 5.1.2 on 2025-03-19 14:17

import apps.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0004_file_summary'),
        ('teams', '0007_create_commcare_connect_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('collection', 'Collection')], default='collection')),
                ('files', models.ManyToManyField(to='files.file')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'type', 'name'), name='unique_repository_per_team')],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
