# Generated by Django 5.1.2 on 2025-04-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('files', '0005_file_is_archived_file_working_version'),
        ('teams', '0007_create_commcare_connect_flag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_collection_per_team',
        ),
        migrations.AddField(
            model_name='collection',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='collection',
            name='working_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.collection'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('team', 'name', 'version_number', 'working_version_id'), name='unique_collection_version_per_team'),
        ),
    ]
