# Generated by Django 5.1.5 on 2025-04-30 05:39

import django.db.models.deletion
from django.db import migrations, models

def _port_collection_files_to_new_field(apps, schema_editor):
        CollectionFilesOld = apps.get_model('documents', 'Collection_files_old')
        CollectionFile = apps.get_model('documents', 'CollectionFile')
        
        for cf in CollectionFilesOld.objects.all().iterator(100):
            CollectionFile.objects.get_or_create(
                collection_id=cf.collection_id,
                file_id=cf.file_id,
            )


def _delete_new_collection_files(apps, schema_editor):
    CollectionFile = apps.get_model('documents', 'CollectionFile')
    CollectionFile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_collection_unique_collection_per_team_and_more'),
        ('files', '0006_remove_file_schema_file_metadata'),
        ('service_providers', '0026_add_google_gemini_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='files',
            new_name='files_old',
        ),
        migrations.AddField(
            model_name='collection',
            name='llm_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_providers.llmprovider', verbose_name='LLM Provider'),
        ),
        migrations.AddField(
            model_name='collection',
            name='openai_vector_store_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_index',
            field=models.BooleanField(default=False),
        ),
        # Add new through model
        migrations.CreateModel(
            name='CollectionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], blank=True, max_length=64)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.collection')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.file')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='files',
            field=models.ManyToManyField(related_name='collections', through='documents.CollectionFile', to='files.file'),
        ),
        # Migrate data from the old through model to the new one
        migrations.RunPython(_port_collection_files_to_new_field, reverse_code=_delete_new_collection_files),
        # Remove old through models
        migrations.RemoveField(
            model_name='collection',
            name='files_old',
        ),
    ]
