# Generated by Django 5.1.5 on 2025-05-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_files_collection_files_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionfile',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
