# Generated by Django 5.1.5 on 2025-05-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_collectionfile_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionfile',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=64),
        ),
    ]
