# Generated by Django 5.1.5 on 2025-05-26 13:32
import apps.documents.datamodels
import apps.documents.models
import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import types
import typing
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_collectionfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionfile',
            name='metadata',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=django_pydantic_field.compat.django.GenericContainer(typing.Union, (
                apps.documents.datamodels.CollectionFileMetadata, types.NoneType))),
        ),
    ]
