# Generated by Django 5.1.5 on 2025-05-28 14:37

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_change_collection_file_metadata'),
    ]

    operations = [
        VectorExtension()
    ]
