# Generated by Django 5.1.5 on 2025-06-02 08:06

import django.db.models.deletion
from django.db import migrations, models

def _make_indexes_remote(apps, schema_editor):
    """All existing indexes are remote, so we have to update them to reflect that."""
    apps.get_model('documents', 'Collection').objects.update(is_remote_index=True)

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_add_pg_vector_extension'),
        ('service_providers', '0028_embeddingprovidermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='embedding_provider_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_embedding_model', to='service_providers.embeddingprovidermodel'),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_remote_index',
            field=models.BooleanField(default=False, help_text='If selected, this index will be created at and hosted by the selected provider'),
        ),
        migrations.RunPython(_make_indexes_remote, migrations.RunPython.noop),
    ]
