# Generated by Django 5.1.5 on 2025-05-30 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_add_pg_vector_extension'),
        ('service_providers', '0028_embeddingprovidermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='embedding_provider_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_embedding_model', to='service_providers.embeddingprovidermodel'),
        ),
    ]
