# Generated by Django 5.1.5 on 2025-07-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_collection_embedding_provider_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='show_file_references',
            field=models.BooleanField(default=False),
        ),
    ]
