# Generated by Django 5.1.5 on 2025-06-02 12:34

from django.db import migrations


def make_indexes_remote(apps, schema_editor):
    apps.get_model('documents', 'Collection').objects.update(is_remote_index=True)

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_collection_embedding_provider_model_and_more'),
    ]

    operations = [
        migrations.RunPython(make_indexes_remote, migrations.RunPython.noop),
    ]
