# Generated by Django 5.1.5 on 2025-07-10 09:47

from django.db import migrations, models


def set_generate_citations_true(apps, schema_editor):
    """Set generate_citations=True for all LLMResponseWithPrompt nodes that have a collection_index_id"""
    Node = apps.get_model('pipelines', 'Node')
    
    nodes_to_update = []
    for idx, node in enumerate(Node.objects.filter(type='LLMResponseWithPrompt').iterator(100)):
        node.params['generate_citations'] = True
        nodes_to_update.append(node)
        
        if idx % 100 == 0:
            Node.objects.bulk_update(nodes_to_update, ['params'])
            nodes_to_update = []


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_collection_embedding_provider_model_and_more'),
        ('pipelines', '0018_add_max_results_node_param'),
    ]

    operations = [
        migrations.RunPython(set_generate_citations_true, migrations.RunPython.noop),
    ]
