# Generated by Django 5.1.5 on 2025-08-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_collectionfile_external_id_documentsource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsource',
            name='source_type',
            field=models.CharField(choices=[('github', 'GitHub Repository'), ('confluence', 'Confluence')], help_text='Type of document source', max_length=20),
        ),
    ]
