# Generated by Django 5.1.5 on 2025-11-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_alter_documentsource_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="summary",
            field=models.TextField(
                blank=True, help_text="Optional description of this collection"
            ),
        ),
    ]
