# Generated by Django 5.1.5 on 2026-03-02 08:29

import apps.documents.datamodels
import django.core.serializers.json
import django_pydantic_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_collection_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionfile",
            name="metadata",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                schema=apps.documents.datamodels.CollectionFileMetadata,
            ),
        ),
    ]
