# Generated by Django 5.2.12 on 2026-04-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_collectionfile_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsource',
            name='source_type',
            field=models.CharField(choices=[('github', 'GitHub Repository'), ('confluence', 'Confluence'), ('json_collection', 'JSON Collection')], help_text='Type of document source', max_length=20),
        ),
    ]
