# Generated by Django 5.2.12 on 2026-03-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_collectionfile_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionfile',
            name='supported_channels',
            field=models.JSONField(blank=True, default=dict, help_text='Channels that cannot send this file directly, with reasons'),
        ),
    ]
