# Generated by Django 5.2.13 on 2026-06-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_alter_documentsource_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='create_version_task_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
