# Generated by Django 5.2.15 on 2026-07-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_collection_create_version_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='contextualizer_strategy',
            field=models.CharField(choices=[('static', 'Static (no LLM, zero cost)'), ('llm', 'LLM-generated')], default='static', max_length=16),
        ),
        migrations.AddField(
            model_name='collection',
            name='enable_contextual_retrieval',
            field=models.BooleanField(default=False, help_text='If enabled, a short context header is generated for each chunk and stored for retrieval.'),
        ),
    ]
