# Generated by Django 5.2.15 on 2026-07-23 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_collection_create_version_task_id'),
        ('service_providers', '0065_alter_voiceprovider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='contextualizer_llm_model',
            field=models.ForeignKey(blank=True, help_text='The chat model used to generate per-chunk context headers when contextual retrieval is enabled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service_providers.llmprovidermodel'),
        ),
        migrations.AddField(
            model_name='collection',
            name='enable_contextual_retrieval',
            field=models.BooleanField(blank=True, help_text='If enabled, a short context header is generated for each chunk and stored for retrieval.', null=True),
        ),
    ]
