# Generated by Django 5.2.15 on 2026-07-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_collection_create_version_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsourcesynclog',
            name='files_failed',
            field=models.IntegerField(default=0, help_text='Number of files that failed to process during sync'),
        ),
        migrations.AlterField(
            model_name='documentsourcesynclog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if sync failed, or per-file failure details'),
        ),
    ]
