# Generated by Django 5.2.13 on 2026-07-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0016_documentsourcesynclog_files_failed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsource",
            name="sync_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When the current sync task acquired its lock.", null=True
            ),
        ),
    ]
