# Generated by Django 5.2.15 on 2026-07-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_collection_contextualizer_llm_model_and_more'),
        ('service_providers', '0065_alter_voiceprovider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='contextualizer_llm_provider',
            field=models.ForeignKey(blank=True, help_text='The LLM provider used with contextualizer_llm_model to generate context headers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service_providers.llmprovider'),
        ),
    ]
