# Generated by Django 5.2.15 on 2026-07-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_documentsourcesynclog_files_failed_and_more'),
        ('documents', '0017_collection_contextualizer_llm_provider'),
    ]

    operations = [
    ]
