# Generated by Django 5.2.15 on 2026-07-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0017_documentsource_sync_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionfile",
            name="failure_reason",
            field=models.TextField(
                blank=True,
                help_text="Why the most recent indexing attempt failed. Cleared when the file is re-indexed.",
            ),
        ),
    ]
