# Generated by Django 5.2.15 on 2026-07-29 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0018_collectionfile_failure_reason"),
        ("service_providers", "0066_add_gemini_3_6_flash_models"),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='contextualizer_llm_model',
            field=models.ForeignKey(blank=True, help_text='The chat model used to generate per-chunk context headers when contextual retrieval is enabled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service_providers.llmprovidermodel'),
        ),
        migrations.AddField(
            model_name='collection',
            name='contextualizer_llm_provider',
            field=models.ForeignKey(blank=True, help_text='The LLM provider used with contextualizer_llm_model to generate context headers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='service_providers.llmprovider'),
        ),
        migrations.AddField(
            model_name='collection',
            name='enable_contextual_retrieval',
            field=models.BooleanField(blank=True, help_text='If enabled, a short context header is generated for each chunk and stored for retrieval.', null=True),
        ),
    ]
