# Generated by Django 5.2.15 on 2026-07-31 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0019_collection_contextualizer_llm_model_and_more"),
        ("files", "0015_filechunkembedding_search_vector"),
        ("service_providers", "0068_traceprovider_metadata"),
        ("teams", "0014_team_is_migrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="search_dense_weight",
            field=models.FloatField(
                blank=True,
                help_text="Weight of dense (semantic) results when fusing with lexical results, between 0 and 1. The lexical ranking receives the remaining weight. Leave blank to use the system default.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="search_fetch_k",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many candidates to retrieve from each of the dense and lexical searches before fusing them. Leave blank to use the system default.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("search_dense_weight__isnull", True),
                    models.Q(("search_dense_weight__gte", 0), ("search_dense_weight__lte", 1)),
                    _connector="OR",
                ),
                name="collection_search_dense_weight_between_0_and_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.CheckConstraint(
                condition=models.Q(("search_fetch_k__isnull", True), ("search_fetch_k__gte", 1), _connector="OR"),
                name="collection_search_fetch_k_at_least_1",
            ),
        ),
    ]
