# Generated by Django 5.2.15 on 2026-07-31 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0019_collection_contextualizer_llm_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="search_dense_weight",
            field=models.FloatField(
                blank=True,
                help_text="Weight of dense (semantic) results when fusing with lexical results, between 0 and 1. The lexical ranking receives the remaining weight. Leave blank to use the system default.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="search_fetch_k",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many candidates to retrieve from each of the dense and lexical searches before fusing them. Leave blank to use the system default.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
