from django.db import transaction
from drf_spectacular.utils import OpenApiExample, extend_schema
from rest_framework.views import APIView

from apps.api.serializers import TriggerBotMessageRequest
from apps.api.v2.serializers import TriggerBotMessageResponse
from apps.api.views.channels import handle_trigger_bot_message


class TriggerBotMessageView(APIView):
    required_scopes = ("chatbots:interact",)

    @extend_schema(
        operation_id="trigger_bot_message",
        summary="Trigger the bot to send a message to the user, or deliver a message directly",
        description=(
            "Send a message to a participant on a channel — either generated by the bot or delivered "
            "verbatim.\n\n"
            "Provide **exactly one** of:\n\n"
            "- **`prompt_text`** — routes through the bot's LLM pipeline; the bot generates the reply "
            "from this prompt.\n"
            "- **`message_text`** — delivered to the participant exactly as written, with no LLM "
            "processing.\n\n"
            "If the participant doesn't exist yet, they are created automatically.\n\n"
            "**Response.** The `channel` field is an object of `{platform, data}`. For CommCare Connect, "
            "`data` carries the `external_channel_id` of the session's Connect channel.\n\n"
            "> **Tip:** The **Request samples** and **Response samples** panels have worked examples for "
            "both modes — pick one from the **Example** dropdown."
        ),
        tags=["Channels"],
        request=TriggerBotMessageRequest(),
        responses={
            200: TriggerBotMessageResponse,
            400: {"description": "Bad Request"},
            404: {"description": "Not Found"},
        },
        examples=[
            OpenApiExample(
                name="GenerateBotMessageAndSend",
                summary="Generates a bot message and sends it to the user (auto-creates participant if needed).",
                value={
                    "identifier": "+15556793",
                    "experiment": "123e4567-e89b-12d3-a456-426614174000",
                    "platform": "whatsapp",
                    "prompt_text": "Tell the user to do something",
                    "session_data": {"key": "value"},
                    "participant_data": {"key": "value"},
                },
                request_only=True,
            ),
            OpenApiExample(
                name="SendMessageDirectly",
                summary="Send a pre-written message directly to the participant, bypassing the bot/LLM.",
                value={
                    "identifier": "+15556793",
                    "experiment": "123e4567-e89b-12d3-a456-426614174000",
                    "platform": "whatsapp",
                    "message_text": "Your appointment is confirmed for tomorrow at 10am.",
                    "session_data": {"key": "value"},
                    "participant_data": {"key": "value"},
                },
                request_only=True,
            ),
            OpenApiExample(
                name="MessageTriggered",
                summary="The session the message will be delivered on, including its channel details.",
                value={
                    "session_id": "123e4567-e89b-12d3-a456-426614174000",
                    "url": "https://example.com/api/sessions/123e4567-e89b-12d3-a456-426614174000/",
                    "team": {"name": "My Team", "slug": "my-team"},
                    "channel": {"platform": "whatsapp", "data": {}},
                },
                response_only=True,
                status_codes=[200],
            ),
            OpenApiExample(
                name="ChannelNotConfigured",
                summary="Experiment cannot send messages on the specified channel",
                value={"detail": "Experiment cannot send messages on the whatsapp channel. Create the channel first."},
                response_only=True,
                status_codes=[400],
            ),
            OpenApiExample(
                name="ConsentNotGiven",
                summary="User has not given consent",
                value={"detail": "User has not given consent"},
                response_only=True,
                status_codes=[400],
            ),
            OpenApiExample(
                name="ExperimentNotFound",
                summary="No experiment with the given ID exists in the team",
                value={"detail": "No Experiment matches the given query."},
                response_only=True,
                status_codes=[404],
            ),
        ],
    )
    @transaction.atomic
    def post(self, request):
        # Not a docstring: the client-facing description lives in @extend_schema above, which
        # drf-spectacular would otherwise override with this docstring.
        return handle_trigger_bot_message(request, TriggerBotMessageResponse)
