/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OpenChatStudioChat {
        "boturl": string;
        "buttonText": string;
        "visible": boolean;
    }
}
declare global {
    interface HTMLOpenChatStudioChatElement extends Components.OpenChatStudioChat, HTMLStencilElement {
    }
    var HTMLOpenChatStudioChatElement: {
        prototype: HTMLOpenChatStudioChatElement;
        new (): HTMLOpenChatStudioChatElement;
    };
    interface HTMLElementTagNameMap {
        "open-chat-studio-widget": HTMLOpenChatStudioChatElement;
    }
}
declare namespace LocalJSX {
    interface OpenChatStudioChat {
        "boturl": string;
        "buttonText"?: string;
        "visible"?: boolean;
    }
    interface IntrinsicElements {
        "open-chat-studio-widget": OpenChatStudioChat;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "open-chat-studio-widget": LocalJSX.OpenChatStudioChat & JSXBase.HTMLAttributes<HTMLOpenChatStudioChatElement>;
        }
    }
}
