# Generated by Django 5.1.15 on 2026-02-13 09:14

import apps.utils.fields
import apps.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0008_drop_unused_waffle_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('schema', apps.utils.fields.SanitizedJSONField(default=dict, help_text='Dict of field_name -> FieldDefinition JSON (same format as evaluator output_schema)')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('team', 'name')},
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
