# Generated by Django 5.1.15 on 2026-02-13 13:35

import apps.utils.fields
import apps.utils.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0023_alter_chatattachment_unique_together'),
        ('experiments', '0130_remove_experiment_llm_provider_and_more'),
        ('teams', '0008_drop_unused_waffle_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('num_reviews_required', models.PositiveSmallIntegerField(default=1, help_text='Number of reviews required before an item is marked complete (1-10)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_annotation_queues', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annotation_queues', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
        migrations.CreateModel(
            name='AnnotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('session', 'Session'), ('message', 'Message'), ('external', 'External Data')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('external_data', apps.utils.fields.SanitizedJSONField(blank=True, default=dict)),
                ('review_count', models.PositiveSmallIntegerField(default=0)),
                ('flags', apps.utils.fields.SanitizedJSONField(blank=True, default=list)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_items', to='chat.chatmessage')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_items', to='experiments.experimentsession')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='human_annotations.annotationqueue')),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
        migrations.CreateModel(
            name='AnnotationSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('schema', apps.utils.fields.SanitizedJSONField(default=dict, help_text='Dict of field_name -> FieldDefinition JSON (same format as evaluator output_schema)')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
        migrations.AddField(
            model_name='annotationqueue',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queues', to='human_annotations.annotationschema'),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', apps.utils.fields.SanitizedJSONField(default=dict, help_text="Annotation data matching the queue's schema")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='submitted', max_length=20)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='human_annotations.annotationitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('item', 'reviewer')},
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
        migrations.AddIndex(
            model_name='annotationitem',
            index=models.Index(fields=['queue', 'status'], name='human_annot_queue_i_b6bf7b_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationitem',
            index=models.Index(fields=['queue', 'created_at'], name='human_annot_queue_i_1266ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='annotationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('queue', 'session'), name='unique_session_per_queue'),
        ),
        migrations.AddConstraint(
            model_name='annotationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('message__isnull', False)), fields=('queue', 'message'), name='unique_message_per_queue'),
        ),
        migrations.AlterUniqueTogether(
            name='annotationschema',
            unique_together={('team', 'name')},
        ),
        migrations.AddConstraint(
            model_name='annotationqueue',
            constraint=models.CheckConstraint(condition=models.Q(('num_reviews_required__gte', 1), ('num_reviews_required__lte', 10)), name='num_reviews_required_range'),
        ),
        migrations.AlterUniqueTogether(
            name='annotationqueue',
            unique_together={('team', 'name')},
        ),
    ]
