# Generated by Django 5.1.15 on 2026-02-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_annotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationitem',
            name='external_data',
        ),
        migrations.AlterField(
            model_name='annotationitem',
            name='item_type',
            field=models.CharField(choices=[('session', 'Session'), ('message', 'Message')], max_length=20),
        ),
    ]
