# Generated by Django 5.1.15 on 2026-02-18 10:26

import apps.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_annotations', '0001_initial'),
        ('teams', '0008_drop_unused_waffle_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationQueueAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggregates', models.JSONField(default=dict, help_text='Aggregated stats per schema field')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('queue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate', to='human_annotations.annotationqueue')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
