# Generated by Django 5.1.15 on 2026-02-13 09:19

import apps.utils.fields
import apps.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_alter_chatattachment_unique_together'),
        ('experiments', '0130_remove_experiment_llm_provider_and_more'),
        ('human_annotations', '0002_annotationqueue'),
        ('teams', '0008_drop_unused_waffle_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('session', 'Session'), ('message', 'Message'), ('external', 'External Data')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('external_data', apps.utils.fields.SanitizedJSONField(blank=True, default=dict)),
                ('review_count', models.PositiveSmallIntegerField(default=0)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_items', to='chat.chatmessage')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='human_annotations.annotationqueue')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_items', to='experiments.experimentsession')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['queue', 'status'], name='human_annot_queue_i_b6bf7b_idx'), models.Index(fields=['queue', 'created_at'], name='human_annot_queue_i_1266ff_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('queue', 'session'), name='unique_session_per_queue'), models.UniqueConstraint(condition=models.Q(('message__isnull', False)), fields=('queue', 'message'), name='unique_message_per_queue')],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
