# Generated by Django 5.2.13 on 2026-05-18 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("human_annotations", "0002_annotationqueueaggregate"),
        ("teams", "0009_merge_pipeline_admin_into_experiment_admin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="authoritative_set_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annotation",
            name="authoritative_set_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authoritative_annotations_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="is_authoritative",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="annotationitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("awaiting_resolution", "Awaiting resolution"),
                    ("completed", "Completed"),
                    ("flagged", "Flagged"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_authoritative", True)),
                fields=("item",),
                name="one_authoritative_annotation_per_item",
            ),
        ),
    ]
