# Generated by Django 5.1.15 on 2026-02-13 09:21

import apps.utils.fields
import apps.utils.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_annotations', '0003_annotationitem'),
        ('teams', '0008_drop_unused_waffle_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', apps.utils.fields.SanitizedJSONField(default=dict, help_text="Annotation data matching the queue's schema")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='submitted', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='human_annotations.annotationitem')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('item', 'reviewer')},
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
