# Generated by Django 5.1.15 on 2026-02-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_annotations', '0004_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationitem',
            name='flag_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
