# Generated by Django 5.1.15 on 2026-02-13 12:30

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_annotations', '0005_add_flag_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationitem',
            name='flag_reason',
        ),
        migrations.AddField(
            model_name='annotationitem',
            name='flags',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=list),
        ),
    ]
