# Generated by Django 5.1.5 on 2025-08-07 13:04

import apps.admin.models
import django.core.serializers.json
import django_pydantic_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', django_pydantic_field.fields.PydanticSchemaField(config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Configuration data', schema=apps.admin.models.SiteConfig)),
            ],
        ),
    ]
