# Generated by Django 4.2.7 on 2024-01-26 15:35

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_avatar"),
    ]

    operations = [
        # Remove audited user manager from migration state to work around account.0006_emailaddress_lower migration
        # which does a data migration using the user model but does not pass the `audit_action` keyword.
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
            ],
        ),
    ]
