# Generated by Django 4.2.7 on 2024-01-26 15:35

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", apps.users.models.AuditedUserObjectManager()),
            ],
        ),
    ]
