# Generated by Django 5.1.5 on 2026-01-14 14:22

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_migrate_2fa_data'),
    ]

    run_before = [
        ('account', '0006_emailaddress_lower')
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'base_manager_name': 'migration_objects'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('migration_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
