# Generated by Django 5.1.5 on 2025-07-09 12:33

import apps.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0007_create_commcare_connect_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('server_url', models.URLField()),
                ('transport_type', models.CharField(choices=[('sse', 'SSE (Server-Sent Events)'), ('streamable_http', 'Streamable HTTP')], default='streamable_http', max_length=20)),
                ('header_name', models.CharField(blank=True, max_length=255)),
                ('header_value', models.CharField(blank=True, max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
