from django.urls import path

from apps.generics.urls import make_crud_urls

from .views import auto_population_views, dataset_views, evaluation_config_views, evaluator_views

app_name = "evaluations"

urlpatterns = [
    path(
        "experiment_versions/",
        evaluation_config_views.load_experiment_versions,
        name="load_experiment_versions",
    ),
    path(
        "<int:evaluation_pk>/runs/new/",
        evaluation_config_views.create_evaluation_run,
        name="create_evaluation_run",
    ),
    path(
        "<int:evaluation_pk>/preview/new/",
        evaluation_config_views.create_evaluation_preview,
        name="create_evaluation_preview",
    ),
    path(
        "<int:evaluation_pk>/evaluation_runs",
        evaluation_config_views.EvaluationRunHome.as_view(),
        name="evaluation_runs_home",
    ),
    path(
        "<int:evaluation_pk>/evaluation_runs_table",
        evaluation_config_views.EvaluationRunTableView.as_view(),
        name="evaluation_runs_table",
    ),
    path(
        "<int:evaluation_pk>/evaluation_trends",
        evaluation_config_views.EvaluationTrendsView.as_view(),
        name="evaluation_trends",
    ),
    path(
        "<int:evaluation_pk>/evaluation_runs/<int:evaluation_run_pk>/results",
        evaluation_config_views.EvaluationResultHome.as_view(),
        name="evaluation_results_home",
    ),
    path(
        "<int:evaluation_pk>/evaluation_runs/<int:evaluation_run_pk>/results_table",
        evaluation_config_views.EvaluationResultTableView.as_view(),
        name="evaluation_results_table",
    ),
    path(
        "<int:evaluation_pk>/evaluation_runs/<int:evaluation_run_pk>/download",
        evaluation_config_views.download_evaluation_run_csv,
        name="evaluation_run_download",
    ),
    path(
        "<int:evaluation_pk>/evaluation_runs/<int:evaluation_run_pk>/update",
        evaluation_config_views.update_evaluation_run_results,
        name="evaluation_run_update",
    ),
    path(
        "sessions_selection_table",
        dataset_views.DatasetSessionsSelectionTableView.as_view(),
        name="dataset_sessions_selection_list",
    ),
    path(
        "sessions_selection_json",
        dataset_views.dataset_sessions_selection_json,
        name="dataset_sessions_selection_json",
    ),
    path(
        "dataset/<int:pk>/add-sessions/",
        dataset_views.EvalDatasetAddSessionsView.as_view(),
        name="dataset_add_sessions",
    ),
    path(
        "dataset/<int:pk>/add-sessions/table/",
        dataset_views.EvalDatasetSessionsTableView.as_view(),
        name="dataset_add_sessions_table",
    ),
    path(
        "dataset/<int:pk>/sessions-count/",
        dataset_views.dataset_sessions_count,
        name="dataset_sessions_count",
    ),
    path(
        "dataset/<int:dataset_id>/messages_table/",
        dataset_views.DatasetMessagesTableView.as_view(),
        name="dataset_messages_table",
    ),
    path(
        "dataset/<int:dataset_id>/add_message/",
        dataset_views.add_message_to_dataset,
        name="add_message_to_dataset",
    ),
    path(
        "add_single_message/session/<str:session_id>/",
        dataset_views.AddMessageToDatasetView.as_view(),
        name="add_single_message_to_dataset",
    ),
    path(
        "message/<int:message_id>/edit_modal/",
        dataset_views.edit_message_modal,
        name="edit_message_modal",
    ),
    path(
        "message/<int:message_id>/update/",
        dataset_views.update_message,
        name="update_message",
    ),
    path(
        "message/<int:message_id>/delete/",
        dataset_views.delete_message,
        name="delete_message",
    ),
    path(
        "parse_csv_columns/",
        dataset_views.parse_csv_columns,
        name="parse_csv_columns",
    ),
    path(
        "<int:evaluation_pk>/evaluation_runs/<int:evaluation_run_pk>/parse_csv_columns/",
        evaluation_config_views.parse_evaluation_results_csv_columns,
        name="parse_evaluation_results_csv_columns",
    ),
    path(
        "dataset/<int:pk>/download/",
        dataset_views.download_dataset_csv,
        name="dataset_download",
    ),
    path(
        "dataset/<int:pk>/upload/",
        dataset_views.upload_dataset_csv,
        name="dataset_upload",
    ),
    path(
        "dataset/<int:pk>/import-from-queue/",
        dataset_views.ImportFromAnnotationQueue.as_view(),
        name="dataset_import_from_queue",
    ),
    path(
        "dataset/<int:dataset_id>/auto_population/new/",
        auto_population_views.CreateAutoPopulationRule.as_view(),
        name="auto_population_rule_new",
    ),
    path(
        "dataset/<int:dataset_id>/auto_population/<int:pk>/",
        auto_population_views.EditAutoPopulationRule.as_view(),
        name="auto_population_rule_edit",
    ),
    path(
        "auto_population/<int:pk>/delete/",
        auto_population_views.DeleteAutoPopulationRule.as_view(),
        name="auto_population_rule_delete",
    ),
    path(
        "auto_population/<int:pk>/toggle/",
        auto_population_views.toggle_auto_population_rule,
        name="auto_population_rule_toggle",
    ),
]

urlpatterns.extend(make_crud_urls(evaluation_config_views, "Evaluation", delete=True))
urlpatterns.extend(make_crud_urls(evaluator_views, "Evaluator", prefix="evaluator"))
urlpatterns.extend(make_crud_urls(dataset_views, "Dataset", prefix="dataset"))
