# Generated by Django 5.1.5 on 2025-04-16 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0110_alter_participantdata_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LLM', 'LLM')], max_length=32)),
                ('params', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('USER_ONLY', 'User Only'), ('BOT_ONLY', 'Bot Only'), ('ALL', 'All')], max_length=32)),
                ('sessions', models.ManyToManyField(to='experiments.experimentsession')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiments.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiments.experiment')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationdataset')),
                ('evaluators', models.ManyToManyField(to='evaluations.evaluator')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationconfig')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.JSONField()),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluator')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='evaluations.evaluationrun')),
            ],
        ),
    ]
