# Generated by Django 5.1.5 on 2025-06-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationrun",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="evaluationrun",
            name="job_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="evaluationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
