# Generated by Django 5.1.5 on 2025-07-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationmessage",
            name="history",
            field=models.JSONField(default=list),
        ),
    ]
