# Generated by Django 5.1.5 on 2025-08-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0002_evaluationconfig_base_experiment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationrun",
            name="type",
            field=models.CharField(
                choices=[("full", "Full"), ("preview", "Preview")],
                db_index=True,
                default="full",
                max_length=20,
            ),
        ),
    ]
