# Generated by Django 5.1.5 on 2025-07-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0003_evaluationconfig_base_experiment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationconfig",
            name="version_selection_type",
            field=models.CharField(
                choices=[
                    ("specific", "Specific Version"),
                    ("latest_working", "Latest Working Version"),
                    ("latest_published", "Latest Published Version"),
                ],
                default="specific",
                help_text="Type of version selection: specific, latest_working, or latest_published",
                max_length=50,
            ),
        ),
    ]
