# Generated by Django 5.1.5 on 2025-09-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_auto_20250903_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationmessage',
            name='participant_data',
            field=models.JSONField(blank=True, default=dict, help_text='Participant data at the time of the message'),
        ),
        migrations.AddField(
            model_name='evaluationmessage',
            name='session_state',
            field=models.JSONField(blank=True, default=dict, help_text='Session state at the time of the trace'),
        ),
    ]
