# Generated by Django 5.1.5 on 2025-10-23 11:10

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_evaluationmessage_participant_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationmessage',
            name='context',
            field=apps.utils.fields.SanitizedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='evaluationmessage',
            name='history',
            field=apps.utils.fields.SanitizedJSONField(default=list),
        ),
        migrations.AlterField(
            model_name='evaluationmessage',
            name='input',
            field=apps.utils.fields.SanitizedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='evaluationmessage',
            name='metadata',
            field=apps.utils.fields.SanitizedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='evaluationmessage',
            name='output',
            field=apps.utils.fields.SanitizedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='evaluationmessage',
            name='participant_data',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=dict, help_text='Participant data at the time of the message'),
        ),
        migrations.AlterField(
            model_name='evaluationmessage',
            name='session_state',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=dict, help_text='Session state at the time of the trace'),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='output',
            field=apps.utils.fields.SanitizedJSONField(),
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='params',
            field=apps.utils.fields.SanitizedJSONField(default=dict),
        ),
    ]
