# Generated by Django 5.1.5 on 2025-10-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0006_alter_evaluationmessage_context_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationdataset",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="evaluationdataset",
            name="job_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="evaluationdataset",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="completed",
                help_text="Status of dataset creation",
                max_length=20,
            ),
        ),
    ]
