# Generated by Django 5.1.5 on 2025-11-17 21:42

from django.db import migrations


def migrate_llm_evaluator_schemas(apps, schema_editor):
    """
    Convert LLM evaluator output_schema from old format to new typed format.
    Old format: {"field_name": "description"}
    New format: {"field_name": {"type": "string", "description": "description"}}
    """
    Evaluator = apps.get_model("evaluations", "Evaluator")

    for evaluator in Evaluator.objects.filter(type="LlmEvaluator"):
        if "output_schema" in evaluator.params:
            output_schema = evaluator.params["output_schema"]
            if output_schema and isinstance(output_schema, dict):
                new_schema = {}
                for field_name, value in output_schema.items():
                    if isinstance(value, str):
                        new_schema[field_name] = {
                            "type": "string",
                            "description": value
                        }
                    else:
                        new_schema[field_name] = value

                if new_schema != output_schema:
                    evaluator.params["output_schema"] = new_schema
                    evaluator.save(update_fields=["params"])


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: convert from new typed format back to old format.
    """
    Evaluator = apps.get_model("evaluations", "Evaluator")

    for evaluator in Evaluator.objects.filter(type="LlmEvaluator"):
        if "output_schema" in evaluator.params:
            output_schema = evaluator.params["output_schema"]
            if output_schema and isinstance(output_schema, dict):
                old_schema = {}
                for field_name, value in output_schema.items():
                    if isinstance(value, dict) and "description" in value:
                        # New format - convert to old
                        old_schema[field_name] = value["description"]
                    else:
                        # Already in old format - keep as is
                        old_schema[field_name] = value

                # Only save if something actually changed
                if old_schema != output_schema:
                    evaluator.params["output_schema"] = old_schema
                    evaluator.save(update_fields=["params"])


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0007_evaluationdataset_error_message_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_llm_evaluator_schemas, reverse_migration),
    ]
