# Generated by Django 5.1.5 on 2025-12-01 19:10

import apps.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0008_auto_20251117_2142"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationRunAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("aggregates", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.evaluator",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregates",
                        to="evaluations.evaluationrun",
                    ),
                ),
            ],
            options={
                "unique_together": {("run", "evaluator")},
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
