# Generated by Django 5.2.12 on 2026-04-23 11:01

import django.db.models.deletion
from django.db import migrations, models

import apps.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0009_alter_tag_category'),
        ('evaluations', '0013_add_evaluation_mode'),
        ('teams', '0009_merge_pipeline_admin_into_experiment_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorTagRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=255)),
                ('condition_type', models.CharField(choices=[('equals', 'Equals'), ('range', 'Range')], max_length=20)),
                ('condition_value', models.JSONField(default=dict)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_rules', to='evaluations.evaluator')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluator_tag_rules', to='annotations.tag')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
        migrations.CreateModel(
            name='AppliedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_tags', to='evaluations.evaluationresult')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotations.tag')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='evaluations.evaluatortagrule')),
            ],
            options={
                'indexes': [models.Index(fields=['rule'], name='evaluations_rule_id_8a4d72_idx')],
                'constraints': [models.UniqueConstraint(fields=('evaluation_result', 'rule', 'tag'), name='unique_applied_tag_per_result_rule')],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
