# Generated by Django 5.2.13 on 2026-05-06 12:51

import apps.utils.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_delete_orphaned_chats'),
        ('evaluations', '0014_add_tag_rules_and_applied_tags'),
        ('experiments', '0134_expsession_team_lastact_idx'),
        ('teams', '0009_merge_pipeline_admin_into_experiment_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationconfig',
            name='auto_run_on_append',
            field=models.BooleanField(default=False, help_text='When enabled, an evaluation run is automatically enqueued for newly appended dataset messages. Each auto-run only evaluates the new rows, but still incurs LLM costs proportional to the number of evaluators and new messages.'),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='scoped_messages',
            field=models.ManyToManyField(blank=True, help_text='When set, this run evaluates only these messages instead of the full dataset. Used by delta runs triggered by dataset appends.', related_name='scoped_evaluation_runs', to='evaluations.evaluationmessage'),
        ),
        migrations.AlterField(
            model_name='evaluationrun',
            name='type',
            field=models.CharField(choices=[('full', 'Full'), ('preview', 'Preview'), ('delta', 'Delta')], db_index=True, default='full', max_length=20),
        ),
        migrations.CreateModel(
            name='DatasetAutoPopulationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_mode', models.CharField(choices=[('message', 'Message'), ('session', 'Session')], help_text="Must match the target dataset's evaluation_mode.", max_length=10)),
                ('filter_query', models.TextField(blank=True, default='', help_text='Query-string-encoded FilterParams (same format used by manual filter import). Empty means no filter beyond the source experiment scope.')),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_ingested_at', models.DateTimeField(default=django.utils.timezone.now, help_text="High-water mark: the periodic task only considers sources newer than this timestamp (minus a small safety margin) on each run. Initialised to the rule's creation time so existing history is not backfilled.")),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('success', 'Success'), ('error', 'Error'), ('no_op', 'No-op')], default='', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('consecutive_failure_count', models.PositiveIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_population_rules', to='evaluations.evaluationdataset')),
                ('source_experiment', models.ForeignKey(help_text='The experiment whose sessions/messages are sampled by this rule.', on_delete=django.db.models.deletion.CASCADE, related_name='dataset_auto_population_rules', to='experiments.experiment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
        migrations.CreateModel(
            name='DatasetIngestionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_entries', to='evaluations.evaluationmessage')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_entries', to='evaluations.datasetautopopulationrule')),
                ('source_message', models.ForeignKey(blank=True, help_text='Set for message-mode ingestion; null for session-mode ingestion.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_entries', to='chat.chatmessage')),
                ('source_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_entries', to='experiments.experimentsession')),
            ],
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
        migrations.AddIndex(
            model_name='datasetautopopulationrule',
            index=models.Index(fields=['is_enabled', 'last_run_at'], name='evaluations_is_enab_afd336_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetingestionentry',
            index=models.Index(fields=['rule', 'created_at'], name='evaluations_rule_id_b74853_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasetingestionentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_message__isnull', False)), fields=('rule', 'source_message'), name='unique_ingestion_per_rule_message'),
        ),
        migrations.AddConstraint(
            model_name='datasetingestionentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_message__isnull', True)), fields=('rule', 'source_session'), name='unique_ingestion_per_rule_session'),
        ),
    ]
