# Generated by Django 5.2.13 on 2026-05-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_add_tag_rules_and_applied_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationconfig',
            name='auto_run_on_append',
            field=models.BooleanField(default=False, help_text='When enabled, every time the dataset receives newly auto-populated rows this evaluation runs automatically over only those rows. May incur LLM cost.'),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='scoped_messages',
            field=models.ManyToManyField(blank=True, help_text='Subset of dataset messages this run evaluated. Empty for FULL/PREVIEW.', related_name='scoping_runs', to='evaluations.evaluationmessage'),
        ),
        migrations.AlterField(
            model_name='evaluationrun',
            name='type',
            field=models.CharField(choices=[('full', 'Full'), ('preview', 'Preview'), ('delta', 'Delta')], db_index=True, default='full', max_length=20),
        ),
    ]
