# Generated by Django 5.2.13 on 2026-05-07 12:44

import apps.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_add_tag_rules_and_applied_tags'),
        ('experiments', '0134_expsession_team_lastact_idx'),
        ('teams', '0009_merge_pipeline_admin_into_experiment_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationconfig',
            name='auto_run_on_append',
            field=models.BooleanField(default=False, help_text='When enabled, every time the dataset receives newly auto-populated rows this evaluation runs automatically over only those rows. May incur LLM cost.'),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='scoped_messages',
            field=models.ManyToManyField(blank=True, help_text='Subset of dataset messages this run evaluated. Empty for FULL/PREVIEW.', related_name='scoping_runs', to='evaluations.evaluationmessage'),
        ),
        migrations.AlterField(
            model_name='evaluationrun',
            name='type',
            field=models.CharField(choices=[('full', 'Full'), ('preview', 'Preview'), ('delta', 'Delta')], db_index=True, default='full', max_length=20),
        ),
        migrations.CreateModel(
            name='DatasetAutoPopulationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filter_query_string', models.TextField(blank=True, help_text="Filter criteria as a query string; empty means 'all sessions from this bot'. Format matches FilterParams used elsewhere.")),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('success', 'Success'), ('error', 'Error'), ('no_op', 'No-op')], max_length=10)),
                ('last_error', models.TextField(blank=True)),
                ('consecutive_failure_count', models.PositiveSmallIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_population_rules', to='evaluations.evaluationdataset')),
                ('source_experiment', models.ForeignKey(help_text='Sessions from this chatbot are considered for auto-population.', on_delete=django.db.models.deletion.CASCADE, related_name='auto_population_rules', to='experiments.experiment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'indexes': [models.Index(fields=['is_enabled', 'last_run_at'], name='evaluations_is_enab_afd336_idx')],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
