# Generated by Django 5.2.15 on 2026-07-24 08:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0015_auto_populate_schema'),
        ('experiments', '0148_alter_syntheticvoice_service'),
        ('teams', '0014_team_is_migrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrun',
            name='batch_dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='evaluator_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='in_flight',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='stall_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='taskbadger_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluationrun',
            name='scoped_messages',
            field=models.ManyToManyField(blank=True, help_text='The frozen message plan for this run (all dataset ids for FULL, the sample for PREVIEW, the explicit list for DELTA).', related_name='scoping_runs', to='evaluations.evaluationmessage'),
        ),
        migrations.AddConstraint(
            model_name='evaluationresult',
            constraint=models.UniqueConstraint(fields=('run', 'message', 'evaluator'), name='unique_result_per_run_message_evaluator'),
        ),
    ]
