# Generated by Django 5.2.13 on 2026-06-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0015_auto_populate_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrun',
            name='tags_archived',
            field=models.BooleanField(db_index=True, default=False, help_text="True when this run's applied tags are no longer the live set — either superseded by a later FULL run or undone. The AppliedTag rows of non-archived runs mirror the live tag state; the active set is always {latest FULL run} ∪ {DELTAs after it}."),
        ),
    ]
