# Generated by Django 5.2.15 on 2026-07-28 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0017_migrate_auto_population_filter_query_strings'),
        ('service_providers', '0067_add_claude_opus_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='llm_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluators', to='service_providers.llmprovider'),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='llm_provider_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluators', to='service_providers.llmprovidermodel'),
        ),
    ]
