# Generated by Django 5.2.15 on 2026-07-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0019_backfill_evaluator_llm_provider_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrun',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text="When the run's completion side effects (aggregates, stale-tag reversal) landed. Set as soon as the run completes if it has nothing to finalize.", null=True),
        ),
    ]
