# Generated by Django 5.1.15 on 2026-01-28 14:46

import apps.utils.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('0', 'Info'), ('1', 'Warning'), ('2', 'Error')], max_length=1)),
                ('last_event_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocs_notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('notification', 'user')},
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notifications', through='ocs_notifications.UserNotification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('in_app_level', models.CharField(choices=[('0', 'Info'), ('1', 'Warning'), ('2', 'Error')], default='0', max_length=20)),
                ('email_enabled', models.BooleanField(default=False)),
                ('email_level', models.CharField(choices=[('0', 'Info'), ('1', 'Warning'), ('2', 'Error')], default='1', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Notification Preferences',
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
