# Generated by Django 5.1.15 on 2026-02-09 14:34

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocs_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='links',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=dict),
        ),
    ]
