# Generated by Django 5.1.15 on 2026-01-28 10:58

import apps.utils.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocs_notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('in_app_level', models.CharField(choices=[('info', 'Info and above'), ('warning', 'Warning and above'), ('error', 'Error only')], default='info', max_length=20)),
                ('email_enabled', models.BooleanField(default=False)),
                ('email_level', models.CharField(choices=[('info', 'Info and above'), ('warning', 'Warning and above'), ('error', 'Error only')], default='warning', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Notification Preferences',
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
