# Generated by Django 5.1.15 on 2026-02-12 07:47

import apps.utils.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocs_notifications', '0002_notification_links'),
        ('teams', '0008_drop_unused_waffle_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='do_not_disturb_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotificationMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_identifier', models.CharField(help_text='Notification identifier to mute', max_length=255)),
                ('muted_until', models.DateTimeField(help_text='When the mute expires. Null means permanent mute.', null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Mutes',
                'indexes': [models.Index(fields=['user', 'team', 'muted_until'], name='ocs_notific_user_id_77110e_idx')],
                'unique_together': {('user', 'team', 'notification_identifier')},
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
