# Generated by Django 5.1.15 on 2026-02-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocs_notifications', '0004_eventtype_eventuser_notificationevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='users',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
