# Generated by Django 5.1.15 on 2026-02-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocs_notifications', '0004_remove_notification_users_delete_usernotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
