# Generated by Django 5.2.16 on 2026-09-01 01:47

import apps.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # The migrations that create the FK targets, not the autodetector's current leaves.
    # A leaf dependency drags service_providers ahead of pipelines in a from-scratch plan,
    # where the notify_deprecated_models data migration queries live models and so reads
    # columns that later migrations have yet to add.
    dependencies = [
        ("ocs_notifications", "0006_eventtype_created_at_index"),
        ("service_providers", "0008_messagingprovider"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel_name", models.CharField(max_length=255)),
                (
                    "channel_id",
                    models.CharField(
                        blank=True,
                        help_text="Resolved Slack channel ID (falls back to the channel name).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Info"), (1, "Warning"), (2, "Error")], default=1
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "messaging_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_channels",
                        to="service_providers.messagingprovider",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification channels",
                "ordering": ("channel_name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "messaging_provider", "level"),
                        name="unique_notification_channel_per_team_provider_and_level",
                    )
                ],
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
    ]
