# Generated by Django 5.2.16 on 2026-09-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocs_notifications", "0007_notificationchannel"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationchannel",
            name="channel_id",
            field=models.CharField(
                blank=True,
                help_text="Resolved Slack channel ID (falls back to the channel name).",
                max_length=255,
                null=True,
            ),
        ),
    ]
