# Generated by Django 5.2.16 on 2026-09-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocs_notifications", "0007_notificationchannel"),
        ("service_providers", "0077_deprecate_gpt5_family"),
        ("teams", "0015_team_created_by"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationchannel",
            name="unique_notification_channel_per_team_and_provider",
        ),
        migrations.AddConstraint(
            model_name="notificationchannel",
            constraint=models.UniqueConstraint(
                fields=("team", "messaging_provider", "level"),
                name="unique_notification_channel_per_team_provider_and_level",
            ),
        ),
    ]
