# Generated by Django 4.2.11 on 2024-06-10 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0005_invitation_groups'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Participant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('identifier', models.CharField(blank=True, max_length=320)),
                        ('public_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                        ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                        ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['identifier'],
                        'unique_together': {('team', 'identifier')},
                    },
                ),
                migrations.CreateModel(
                    name='ParticipantData',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('data', django_cryptography.fields.encrypt(models.JSONField(default=dict))),
                        ('object_id', models.PositiveIntegerField()),
                        ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                        ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_set', to='participants.participant')),
                        ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                    ],
                    options={
                        'indexes': [models.Index(fields=['content_type', 'object_id'], name='participant_content_55e152_idx')],
                        'unique_together': {('participant', 'content_type', 'object_id')},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
