# Generated by Django 4.2 on 2023-11-02 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("experiments", "0051_remove_experiment_llm_provider"),
        ("llm_providers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LlmProvider",
        ),
    ]
