# Generated by Django 4.2 on 2023-10-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_flag"),
        ("llm_providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmprovider",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="llm_providers_old", to="teams.team"
            ),
        ),
    ]
