# Generated by Django 4.2 on 2023-11-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("teams", "0004_membership_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups to assign to the user when they accept the invitation.",
                to="auth.group",
                verbose_name="Groups",
            ),
        ),
    ]
