# Generated by Django 4.2.11 on 2024-07-05 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0005_invitation_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="role",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="role",
        ),
    ]
