# Generated by Django 4.2.15 on 2024-08-20 11:41

from django.db import migrations


def create_events_and_pipelines_v2_flag(apps, schema_editor):
    Flag = apps.get_model("teams", "Flag")
    new_flag = Flag.objects.create(name="events_and_pipelines_v2", everyone=False)
    events_flag = Flag.objects.get(name="events")
    pipelines_v2_flag = Flag.objects.get(name="pipelines-v2")
    new_flag.teams.add(*pipelines_v2_flag.teams.all())
    new_flag.teams.add(*events_flag.teams.all())


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_invitation_role_remove_membership_role'),
    ]

    operations = [
        migrations.RunPython(create_events_and_pipelines_v2_flag, migrations.RunPython.noop, elidable=True),
    ]
