# Generated by Django 5.1.2 on 2025-01-15 08:09

from django.db import migrations


def create_commcare_connect_flag(apps, schema_editor):
    Flag = apps.get_model('teams', 'Flag')
    Flag.objects.create(name='commcare_connect', everyone=False)

def remove_commcare_connect_flag(apps, schema_editor):
    Flag = apps.get_model('teams', 'Flag')
    Flag.objects.filter(name='commcare_connect').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_invitation_role_remove_membership_role'),
    ]

    operations = [
        migrations.RunPython(create_commcare_connect_flag, remove_commcare_connect_flag),
    ]