# Generated by Django 5.1.2 on 2025-01-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_invitation_role_remove_membership_role'),
    ]

    operations = [
    ]
