# Generated by Django 5.2.13 on 2026-06-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0010_create_flag_ai_cost_monitoring"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="public_key",
            field=models.TextField(
                blank=True, default="", help_text="Public key used to seal data exported from this team."
            ),
        ),
    ]
