# Generated by Django 5.2.13 on 2026-06-23 12:41

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_team_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='metadata',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=dict, help_text='Internal staff-only metadata for this team.'),
        ),
    ]
