# Generated by Django 5.2.13 on 2026-07-01 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_file_unsupported_channels'),
        ('teams', '0012_team_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='files_export',
            field=models.ForeignKey(blank=True, help_text='Most recently generated team-files export, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.file'),
        ),
        migrations.AddField(
            model_name='team',
            name='files_export_task_id',
            field=models.CharField(blank=True, default='', help_text='Celery task id of an in-progress team-files export, if any.', max_length=255),
        ),
    ]
