# Generated by Django 5.2.13 on 2026-07-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0013_team_files_export_team_files_export_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_migrating",
            field=models.BooleanField(
                default=False,
                db_default=False,
                help_text="When set, the team's outbound message firing is frozen while its data is migrated.",
            ),
        ),
    ]
