# Generated by Django 5.2.16 on 2026-08-20 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_team_created_by(apps, schema_editor):
    """Use each historical team's earliest membership as its creator."""
    Team = apps.get_model("teams", "Team")
    Membership = apps.get_model("teams", "Membership")
    first_membership_user = (
        Membership.objects.filter(team_id=OuterRef("pk")).order_by("created_at", "pk").values("user_id")[:1]
    )
    Team.objects.filter(created_by__isnull=True).update(created_by_id=Subquery(first_membership_user))


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0014_team_is_migrating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User who created this team, if known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_team_created_by, migrations.RunPython.noop),
    ]
