# Generated by Django 5.2.16 on 2026-09-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0016_reduce_flag_inputs_to_everyone_and_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="require_mfa",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="When set, every member of this team must enrol in two-factor authentication.",
            ),
        ),
    ]
