# Generated by Django 4.2 on 2023-06-20 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("bot_channels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentchannel",
            name="external_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
