# Generated by Django 4.2 on 2023-07-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("experiments", "0023_syntheticvoice_experiment_synthetic_voice"),
        ("bot_channels", "0003_alter_experimentchannel_extra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentchannel",
            name="platform",
            field=models.CharField(choices=[("telegram", "telegram")], default="telegram", max_length=32),
        ),
        migrations.CreateModel(
            name="ChannelSession",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_chat_id", models.CharField()),
                (
                    "experiment_channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_sessions",
                        to="bot_channels.experimentchannel",
                    ),
                ),
                (
                    "experiment_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_session",
                        to="experiments.experimentsession",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
