# Generated by Django 4.2 on 2023-07-26 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chat_external_chat_id"),
        ("bot_channels", "0004_experimentchannel_platform_channelsession"),
    ]

    # operations removed along with ChannelSession model
    operations = []
