# Generated by Django 4.2 on 2023-08-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_channels", "0005_create_channel_sessions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentchannel",
            name="platform",
            field=models.CharField(
                choices=[("telegram", "telegram"), ("web", "web")], default="telegram", max_length=32
            ),
        ),
    ]
