# Generated by Django 4.2 on 2023-08-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_channels", "0006_alter_experimentchannel_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentchannel",
            name="platform",
            field=models.CharField(
                choices=[("telegram", "telegram"), ("web", "web"), ("whatsapp", "whatsapp")],
                default="telegram",
                max_length=32,
            ),
        ),
    ]
