# Generated by Django 4.2 on 2023-10-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_channels", "0007_alter_experimentchannel_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentchannel",
            name="platform",
            field=models.CharField(
                choices=[("telegram", "Telegram"), ("web", "Web"), ("whatsapp", "WhatsApp")],
                default="telegram",
                max_length=32,
            ),
        ),
    ]
