# Generated by Django 4.2 on 2023-10-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_channels", "0009_alter_experimentchannel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelsession",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="experimentchannel",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
