# Generated by Django 4.2 on 2023-11-02 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot_channels", "0010_alter_channelsession_id_alter_experimentchannel_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChannelSession",
        ),
    ]
