# Generated by Django 4.2.7 on 2024-02-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_channels", "0013_alter_experimentchannel_platform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experimentchannel",
            name="active",
        ),
        migrations.AddField(
            model_name="experimentchannel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
