# Generated by Django 4.2.11 on 2024-06-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot_channels", "0016_alter_experimentchannel_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentchannel",
            name="platform",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("web", "Web"),
                    ("whatsapp", "WhatsApp"),
                    ("facebook", "Facebook"),
                    ("api", "API"),
                    ("slack", "Slack"),
                ],
                default="telegram",
                max_length=32,
            ),
        ),
    ]
