# Generated by Django 4.2.14 on 2024-07-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_channels', '0017_alter_experimentchannel_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentchannel',
            name='platform',
            field=models.CharField(
                choices=[
                    ('telegram', 'Telegram'),
                    ('web', 'Web'),
                    ('whatsapp', 'WhatsApp'),
                    ('facebook', 'Facebook'),
                    ('sureadhere', 'SureAdhere'),
                    ('api', 'API'),
                    ('slack', 'Slack')
                ], default='telegram',
                max_length=32
            ),
        ),
    ]
