# Generated by Django 4.2.15 on 2024-08-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0019_experimentchannel_team"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="experimentchannel",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted", False), ("platform__in", ["api", "web"])
                ),
                fields=("team", "platform"),
                name="unique_global_channel_per_team",
            ),
        ),
    ]
