# Generated by Django 5.1.2 on 2025-01-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_channels', '0020_experimentchannel_unique_global_channel_per_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentchannel',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Web'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('sureadhere', 'SureAdhere'), ('api', 'API'), ('slack', 'Slack'), ('commcare_connect', 'CommCare Connect')], default='telegram', max_length=32),
        ),
    ]
