# Generated by Django 5.1.5 on 2025-05-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_channels', '0021_alter_experimentchannel_platform'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='experimentchannel',
                    table='channels_experimentchannel',
                ),
            ]
        )
    ]
