# Generated by Django 5.1.5 on 2025-07-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_channels", "0022_alter_experimentchannel_table"),
        ("experiments", "0113_experiment_experiments_team_id_e83039_idx_and_more"),
        ("service_providers", "0031_deprecate_claude_opus_3"),
        ("teams", "0007_create_commcare_connect_flag"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="experimentchannel",
            name="unique_global_channel_per_team",
        ),
        migrations.AlterField(
            model_name="experimentchannel",
            name="platform",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("web", "Web"),
                    ("whatsapp", "WhatsApp"),
                    ("facebook", "Facebook"),
                    ("sureadhere", "SureAdhere"),
                    ("api", "API"),
                    ("slack", "Slack"),
                    ("commcare_connect", "CommCare Connect"),
                    ("evaluations", "Evaluations"),
                ],
                default="telegram",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="experimentchannel",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted", False), ("platform__in", ["api", "web", "evaluations"])
                ),
                fields=("team", "platform"),
                name="unique_global_channel_per_team",
            ),
        ),
    ]
