# Generated by Django 5.1.5 on 2025-09-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_channels', '0023_remove_experimentchannel_unique_global_channel_per_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentchannel',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Web'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('sureadhere', 'SureAdhere'), ('api', 'API'), ('slack', 'Slack'), ('commcare_connect', 'CommCare Connect'), ('evaluations', 'Evaluations'), ('embedded_widget', 'Embedded Widget')], default='telegram', max_length=32),
        ),
    ]
