# Generated by Django 5.2.12 on 2026-04-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_channels', '0024_alter_experimentchannel_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentchannel',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Web'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('sureadhere', 'SureAdhere'), ('api', 'API'), ('slack', 'Slack'), ('commcare_connect', 'CommCare Connect'), ('evaluations', 'Evaluations'), ('embedded_widget', 'Embedded Widget'), ('email', 'Email')], default='telegram', max_length=32),
        ),
    ]
