# Generated by Django 5.2.13 on 2026-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_channels', '0025_alter_experimentchannel_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentchannel',
            name='widget_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='experimentchannel',
            name='widget_version_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
