# Generated by Django 5.2.15 on 2026-07-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_channels', '0029_experimentchannel_required_auth_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentchannel',
            name='auth_level_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentchannel',
            name='pending_auth_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'None (pre-0.5.1 legacy)'), (1, 'Embed key only (0.5.1 – 0.8.x)'), (2, 'Session token required (0.9.0+)')], null=True),
        ),
    ]
