# Generated by Django 5.2.16 on 2026-08-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    # Only this app's own previous migration: everything here touches columns on
    # channels_experimentchannel alone. The autodetector's extra cross-app dependencies
    # pull service_providers ahead of pipelines in a from-scratch plan, where the
    # notify_deprecated_models data migration then queries a column that does not exist yet.
    dependencies = [
        ('bot_channels', '0032_experimentchannel_enabled_disabled_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentchannel',
            name='credential_mode',
            field=models.CharField(choices=[('embed_key', 'Embed key (public widget)'), ('oauth', 'OAuth token')], default='embed_key', help_text='What a caller must present to start a chat session on this channel.', max_length=32),
        ),
        migrations.AddField(
            model_name='experimentchannel',
            name='session_token_lifetime',
            field=models.DurationField(blank=True, help_text='How long a chat session stays usable after it is created. Leave blank to use the system default. Format: <code>HH:MM:SS</code>, or <code>D HH:MM:SS</code> for days (e.g. <code>12:00:00</code> for 12 hours, <code>2 00:00:00</code> for 2 days).', null=True, verbose_name='Session lifetime'),
        ),
        migrations.AlterField(
            model_name='experimentchannel',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Web'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('sureadhere', 'SureAdhere'), ('api', 'API'), ('slack', 'Slack'), ('commcare_connect', 'CommCare Connect'), ('evaluations', 'Evaluations'), ('embedded_widget', 'Chat Widget & API'), ('email', 'Email')], default='telegram', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='experimentchannel',
            constraint=models.CheckConstraint(condition=models.Q(('credential_mode', 'embed_key'), ('required_auth_level', 2), _connector='OR'), name='oauth_credential_mode_requires_session_token'),
        ),
    ]
