# Generated by Django 5.2.16 on 2026-08-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_channels", "0033_experimentchannel_credential_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentchannel",
            name="platform",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("web", "Web"),
                    ("whatsapp", "WhatsApp"),
                    ("facebook", "Facebook"),
                    ("sureadhere", "SureAdhere"),
                    ("api", "API"),
                    ("slack", "Slack"),
                    ("commcare_connect", "CommCare Connect"),
                    ("evaluations", "Evaluations"),
                    ("embedded_widget", "Chat Widget & API"),
                    ("email", "Email"),
                    ("public", "Public link"),
                ],
                default="telegram",
                max_length=32,
            ),
        ),
    ]
