# Generated by Django 5.2.16 on 2026-08-27 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot_channels", "0034_alter_experimentchannel_platform"),
        ("bot_channels", "0034_notify_widget_version_release_0_12_0"),
    ]

    operations = []
