# Generated by Django 5.2.16 on 2026-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_channels', '0035_merge_20260827_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentchannel',
            name='session_token_lifetime',
            field=models.DurationField(blank=True, help_text='How long each session token issued for this channel stays usable. Leave blank to use the system default. Format: <code>HH:MM:SS</code>, or <code>D HH:MM:SS</code> for days (e.g. <code>12:00:00</code> for 12 hours, <code>2 00:00:00</code> for 2 days).', null=True, verbose_name='Session lifetime'),
        ),
    ]
