# Generated by Django 5.2.15 on 2026-07-23 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_oauth2application_authorization_grant_type'),
        ('teams', '0014_team_is_migrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2application',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
