# Generated by Django 5.2.16 on 2026-08-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experiments", "0149_expsession_team_lastact_c_idx"),
        ("oauth", "0003_oauth2application_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauth2application",
            name="allowed_chatbots",
            field=models.ManyToManyField(
                blank=True,
                help_text="Chatbots this application may start chat sessions with. Empty means none.",
                related_name="oauth_applications",
                to="experiments.experiment",
            ),
        ),
    ]
