# Generated by Django 5.1.5 on 2025-05-27 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the banner', max_length=100)),
                ('message', models.TextField(help_text='Display message rendered as markdown')),
                ('banner_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('danger', 'Danger'), ('success', 'Success')], default='info', help_text='Visual style of the banner', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this banner should start being displayed')),
                ('end_date', models.DateTimeField(help_text='When this banner should stop being displayed')),
                ('is_active', models.BooleanField(default=True, help_text='Manually enable/disable this banner')),
                ('location', models.CharField(choices=[('global', 'Global (All Pages)'), ('experiments_home', 'Experiments Home'), ('experiments_new', 'New Experiments'), ('pipelines', 'Pipelines Home'), ('pipelines_new', 'New Pipelines'), ('chatbots_home', 'Chatbots Home'), ('chatbots_new', 'New Chatbot'), ('assistants_home', 'Assistants Home'), ('team_settings', 'Team Settings')], default='global', help_text='Location of banner on site', max_length=100)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-end_date'],
            },
        ),
    ]
