# Generated by Django 5.1.5 on 2025-05-28 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
        migrations.swappable_dependency(settings.WAFFLE_FLAG_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='feature_flag',
            field=models.ForeignKey(blank=True, help_text='Banner will only show if team has the flag enabled', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.WAFFLE_FLAG_MODEL),
        ),
    ]
