# Generated by Django 5.1.5 on 2025-10-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_banner_dismiss_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='location',
            field=models.CharField(choices=[('global', 'Global (All Pages)'), ('pipelines', 'Pipelines Home'), ('pipelines_new', 'New Pipelines'), ('chatbots_home', 'Chatbots Home'), ('chatbots_new', 'New Chatbot'), ('assistants_home', 'Assistants Home'), ('team_settings', 'Team Settings')], default='global', help_text='Location of banner on site', max_length=100),
        ),
    ]
