# Generated by Django 5.1.5 on 2026-01-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_alter_banner_location'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The site where the banner will be displayed. Leave blank for all sites.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
