# Generated by Django 5.2.16 on 2026-09-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_banner_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='location',
            field=models.CharField(choices=[('global', 'Global (All Pages)'), ('pipelines', 'Pipelines Home'), ('pipelines_new', 'New Pipelines'), ('chatbots_home', 'Chatbots Home'), ('chatbots_new', 'New Chatbot'), ('team_settings', 'Team Settings')], default='global', help_text='Location of banner on site', max_length=100),
        ),
    ]
