
/**
* This file and all schema files were automatically generated by generate_pipeline_schemas.
* DO NOT MODIFY IT BY HAND. Instead, modify the pipeline node classes in Python,
* and run generate_pipeline_schemas to regenerate this file.
*/import BooleanNode from "../schemas/BooleanNode.json"
import ExtractParticipantData from "../schemas/ExtractParticipantData.json"
import ExtractStructuredData from "../schemas/ExtractStructuredData.json"
import LLMResponse from "../schemas/LLMResponse.json"
import LLMResponseWithPrompt from "../schemas/LLMResponseWithPrompt.json"
import Passthrough from "../schemas/Passthrough.json"
import RenderTemplate from "../schemas/RenderTemplate.json"
import RouterNode from "../schemas/RouterNode.json"
import SendEmail from "../schemas/SendEmail.json"


export const NodeTypeSchemas: Record<string, any> = {
    BooleanNode: BooleanNode,
    ExtractParticipantData: ExtractParticipantData,
    ExtractStructuredData: ExtractStructuredData,
    LLMResponse: LLMResponse,
    LLMResponseWithPrompt: LLMResponseWithPrompt,
    Passthrough: Passthrough,
    RenderTemplate: RenderTemplate,
    RouterNode: RouterNode,
    SendEmail: SendEmail,
};