
/**
* This file and all schema files were automatically generated by generate_pipeline_schemas.
* DO NOT MODIFY IT BY HAND. Instead, modify the pipeline node classes in Python,
* and run generate_pipeline_schemas to regenerate this file.
*/
import Ajv from "ajv"
import BooleanNode from "../schemas/BooleanNode.json"
import ExtractParticipantData from "../schemas/ExtractParticipantData.json"
import ExtractStructuredData from "../schemas/ExtractStructuredData.json"
import LLMResponse from "../schemas/LLMResponse.json"
import LLMResponseWithPrompt from "../schemas/LLMResponseWithPrompt.json"
import Passthrough from "../schemas/Passthrough.json"
import RenderTemplate from "../schemas/RenderTemplate.json"
import RouterNode from "../schemas/RouterNode.json"
import SendEmail from "../schemas/SendEmail.json"


const ajv = new Ajv({
    // this is needed 'validators' and 'help_text' fields in the schema. Ideally these would be replaced with
    // JSON schema validations and using the 'description' field in the schema.
    strict: false,
    allErrors: true,
});
ajv.addSchema(BooleanNode, "BooleanNode");
ajv.addSchema(ExtractParticipantData, "ExtractParticipantData");
ajv.addSchema(ExtractStructuredData, "ExtractStructuredData");
ajv.addSchema(LLMResponse, "LLMResponse");
ajv.addSchema(LLMResponseWithPrompt, "LLMResponseWithPrompt");
ajv.addSchema(Passthrough, "Passthrough");
ajv.addSchema(RenderTemplate, "RenderTemplate");
ajv.addSchema(RouterNode, "RouterNode");
ajv.addSchema(SendEmail, "SendEmail");


export default ajv;