# Generated by Django 5.1.2 on 2024-11-05 18:15

import apps.utils.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assistants", "0007_openaiassistant_tools"),
        ("experiments", "0098_alter_experimentroute_unique_together_and_more"),
        ("service_providers", "0018_alter_authprovider_type"),
        ("teams", "0006_remove_invitation_role_remove_membership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("prompt", models.TextField(blank=True)),
                ("server_url", models.URLField()),
                ("api_schema", models.JSONField()),
                ("_operations", models.JSONField(default=list)),
                (
                    "allowed_operations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "auth_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_actions",
                        to="service_providers.authprovider",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
            bases=(models.Model, apps.utils.models.VersioningMixin),
        ),
        migrations.CreateModel(
            name="CustomActionOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_id", models.CharField(max_length=255)),
                (
                    "assistant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_action_operations",
                        to="assistants.openaiassistant",
                    ),
                ),
                (
                    "custom_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom_actions.customaction",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_action_operations",
                        to="experiments.experiment",
                    ),
                ),
            ],
            options={
                "ordering": ("operation_id",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("experiment", "custom_action", "operation_id"),
                        name="unique_experiment_custom_action_operation",
                    ),
                    models.UniqueConstraint(
                        fields=("assistant", "custom_action", "operation_id"),
                        name="unique_assistant_custom_action_operation",
                    ),
                ],
            },
        ),
    ]
