# Generated by Django 5.1.15 on 2026-01-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_actions', '0003_remove_customactionoperation_experiment_or_assistant_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customaction',
            name='health_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('up', 'Up'), ('down', 'Down')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='customaction',
            name='healthcheck_path',
            field=models.CharField(blank=True, default='', help_text='Optional health check endpoint'),
        ),
        migrations.AddField(
            model_name='customaction',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
