# Generated by Django 5.1.2 on 2024-11-26 08:47

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_external_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
