# Generated by Django 5.1.5 on 2025-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='summary',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='file',
            name='purpose',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('collection', 'Collection')], default='assistant', max_length=255),
            preserve_default=False,
        ),
    ]
