# Generated by Django 5.1.2 on 2025-03-31 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='working_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.file'),
        ),
    ]
