# Generated by Django 5.1.2 on 2025-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='summary',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
