# Generated by Django 5.1.5 on 2025-04-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_is_archived_file_working_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='schema',
        ),
        migrations.AddField(
            model_name='file',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
