# Generated by Django 5.1.5 on 2025-06-11 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_filechunkembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechunkembedding',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filechunkembedding',
            name='working_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.filechunkembedding'),
        ),
    ]
