# Generated by Django 5.1.5 on 2025-06-11 12:47

import pgvector.django.halfvec
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_filechunkembedding_is_archived_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filechunkembedding',
            name='embedding_index',
        ),
        migrations.AlterField(
            model_name='filechunkembedding',
            name='embedding',
            field=pgvector.django.halfvec.HalfVectorField(dimensions=1024),
        ),
        # The Django ORM doesn't seem to support Half vector field with HNSW, so we need to use raw SQL for the index creation.
        migrations.RunSQL(
            sql="""
                CREATE INDEX embedding_index
                ON files_filechunkembedding
                USING hnsw ((embedding::halfvec(1024)) halfvec_cosine_ops)
                WITH (m = 16, ef_construction = 64);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS embedding_index;
            """
        ),
    ]
