# Generated by Django 5.1.5 on 2025-10-23 11:10

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_filechunkembedding_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='metadata',
            field=apps.utils.fields.SanitizedJSONField(default=dict),
        ),
    ]
