# Generated by Django 5.1.5 on 2025-10-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0009_alter_file_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("assistant", "Assistant"),
                    ("collection", "Collection"),
                    ("evaluation_dataset", "Evaluation Dataset"),
                ],
                max_length=255,
            ),
        ),
    ]
