# Generated by Django 5.1.5 on 2025-12-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_file_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='purpose',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('collection', 'Collection'), ('evaluation_dataset', 'Evaluation Dataset'), ('data_export', 'Data Export')], max_length=255),
        ),
    ]
