# Generated by Django 5.1.15 on 2026-01-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_alter_file_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='purpose',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('collection', 'Collection'), ('evaluation_dataset', 'Evaluation Dataset'), ('data_export', 'Data Export'), ('message_media', 'Message Media')], max_length=255),
        ),
    ]
