# Generated by Django 5.2.12 on 2026-03-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_alter_file_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='unsupported_channels',
            field=models.JSONField(blank=True, default=dict, help_text='Channels that cannot send this file directly, with reasons'),
        ),
    ]
