# Generated by Django 5.2.15 on 2026-07-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_file_unsupported_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechunkembedding',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
