import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    """Add the lexical search column for hybrid search.

    Kept atomic and index-free on purpose. The GIN index is built concurrently in the migration
    that follows, which has to run outside a transaction; combining the two would make this
    migration non-re-runnable, because the column add would commit on its own while the
    ``django_migrations`` row is only written once every operation succeeds. A failed index build
    would then leave the retry failing with "column search_vector already exists".

    The column is populated by the indexing pipeline rather than generated by Postgres, so adding
    it is a metadata-only change: no table rewrite, no backfill of existing rows. Chunks indexed
    before this migration have a NULL vector and are invisible to lexical search until re-indexed;
    dense retrieval is unaffected, and hybrid search degrades to dense-only for them.
    """

    dependencies = [
        ("files", "0014_filechunkembedding_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="filechunkembedding",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
