# Generated by Django 5.2.15 on 2026-07-31 05:54

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the lexical half of hybrid search to file chunks.

    Operator notes:

    * ``AddField`` for a stored generated column rewrites ``files_filechunkembedding``
      once, holding an ACCESS EXCLUSIVE lock for the duration. That backfills
      ``search_vector`` for every existing row, so no data migration is needed. Expect the
      rewrite to scale with table size -- on a large chunk table plan for a maintenance
      window rather than running this during peak traffic.
    * The GIN index is built with ``CREATE INDEX CONCURRENTLY`` so it does not block
      writes. That requires this migration to run outside a transaction, hence
      ``atomic = False``. A concurrent build that fails leaves an INVALID index behind
      which must be dropped before retrying.
    """

    atomic = False

    dependencies = [
        ("files", "0014_filechunkembedding_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="filechunkembedding",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector("context", "text", config="simple"),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        AddIndexConcurrently(
            model_name="filechunkembedding",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="file_chunk_search_vector_idx"
            ),
        ),
    ]
