# Generated by Django 5.2.16 on 2026-09-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_filechunkembedding_search_vector_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='purpose',
            field=models.CharField(choices=[('collection', 'Collection'), ('evaluation_dataset', 'Evaluation Dataset'), ('data_export', 'Data Export'), ('message_media', 'Message Media')], max_length=255),
        ),
    ]
