# Generated by Django 5.2.16 on 2026-09-22 16:23

from django.db import migrations, models

import apps.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0021_collection_reranking_settings"),
        ("files", "0017_alter_file_purpose"),
        ("teams", "0018_delete_assistant_admin_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="filechunkembedding",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="filechunkembedding",
            name="metadata",
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=None, null=True),
        ),
    ]
