# Generated by Django 4.2 on 2023-06-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="external_chat_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
