# Generated by Django 4.2 on 2023-07-27 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chat_external_chat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="external_chat_id",
        ),
    ]
