# Generated by Django 4.2 on 2023-08-08 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_remove_chat_external_chat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FutureMessage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.CharField()),
                ("due_at", models.DateTimeField()),
                ("interval_minutes", models.IntegerField(blank=True, null=True)),
                ("end_date", models.DateTimeField()),
                ("resolved", models.BooleanField(default=False)),
                (
                    "experiment_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="future_messages",
                        to="experiments.experimentsession",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
