# Generated by Django 4.2 on 2023-10-08 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_futuremessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FutureMessage",
        ),
    ]
