# Generated by Django 4.2 on 2023-10-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_chat_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
