# Generated by Django 4.2.7 on 2024-01-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_alter_chat_id_alter_chatmessage_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="The summary of the conversation up to this point (not including this message)",
                null=True,
            ),
        ),
    ]
