# Generated by Django 4.2.7 on 2024-03-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_celery_periodic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="name",
            field=models.CharField(default="Unnamed Chat", max_length=128),
        ),
    ]
