# Generated by Django 4.2.7 on 2024-03-18 12:59

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
        ('chat', '0011_alter_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='annotations.CustomTaggedItem', to='annotations.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='annotations.CustomTaggedItem', to='annotations.Tag', verbose_name='Tags'),
        ),
    ]
