# Generated by Django 4.2.7 on 2024-03-12 08:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('annotations', '0001_initial'),
        ('chat', '0011_alter_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='annotations.CustomTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
