# Generated by Django 4.2.7 on 2024-03-14 12:16

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('annotations', '0002_alter_tag_options'),
        ('chat', '0012_chat_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='annotations.CustomTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
