# Generated by Django 4.2.7 on 2024-04-29 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_invitation_groups'),
        ('experiments', '0078_alter_participant_external_chat_id'),
        ('chat', '0012_chat_tags_chatmessage_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('trigger_event', models.CharField(choices=[('participant_joined', 'A new participant joined the experiment')], db_index=True)),
                ('recurring', models.BooleanField()),
                ('time_period', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')])),
                ('frequency', models.IntegerField(default=1)),
                ('repetitions', models.IntegerField(default=0)),
                ('prompt_text', models.TextField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_message_configs', to='experiments.experiment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_trigger_date', models.DateTimeField(null=True)),
                ('last_triggered_at', models.DateTimeField(null=True)),
                ('total_triggers', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schduled_messages', to='experiments.participant')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='chat.scheduledmessageconfig')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'indexes': [models.Index(fields=['is_complete'], name='chat_schedu_is_comp_92cfd3_idx')],
            },
        ),
    ]
