# Generated by Django 4.2.7 on 2024-05-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_chat_tags_chatmessage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
    ]
