# Generated by Django 5.1.5 on 2025-07-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0008_alter_tag_category'),
        ('chat', '0019_chatmessage_chat_chatme_chat_id_45c5e0_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'message_type', 'created_at'], name='chat_chatme_chat_id_4753eb_idx'),
        ),
    ]
