# Generated by Django 5.1.5 on 2025-10-23 11:10

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_chatmessage_chat_chatme_chat_id_45c5e0_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='metadata',
            field=apps.utils.fields.SanitizedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='chatattachment',
            name='extra',
            field=apps.utils.fields.SanitizedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='metadata',
            field=apps.utils.fields.SanitizedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='translations',
            field=apps.utils.fields.SanitizedJSONField(default=dict, help_text='Dictionary of translated text keyed by the language code'),
        ),
    ]
