# Generated by Django 5.1.5 on 2025-11-14 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_alter_chat_metadata_alter_chatattachment_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
