# Generated by Django 5.1.15 on 2026-02-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_alter_chatmessage_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatattachment',
            unique_together={('chat', 'tool_type')},
        ),
    ]
