# Generated by Django 5.1.15 on 2026-02-12 06:42

from django.db import migrations

from apps.data_migrations.utils.migrations import RunDataMigration


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_alter_chatmessage_created_at'),
        ('data_migrations', '0001_initial'),
    ]

    operations = [
        RunDataMigration("merge_duplicate_chat_attachments"),
    ]
