# Generated by Django 5.2.12 on 2026-03-06 08:36

from django.db import migrations


def delete_orphaned_chats(apps, schema_editor):
    """Delete Chat objects that have no associated ExperimentSession.

    These orphaned Chats were left behind when evaluation sessions were
    cleaned up without also deleting the linked Chat (and its messages).
    """
    Chat = apps.get_model("chat", "Chat")
    Chat.objects.filter(experiment_session__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0023_alter_chatattachment_unique_together"),
    ]

    operations = [
        migrations.RunPython(delete_orphaned_chats, migrations.RunPython.noop),
    ]
