# Generated by Django 5.2.12 on 2026-03-06 08:36

from django.db import migrations


def delete_orphaned_chats(apps, schema_editor):
    """Delete Chat objects that have no associated ExperimentSession.

    These orphaned Chats were left behind when evaluation sessions were
    cleaned up without also deleting the linked Chat (and its messages).
    """
    Chat = apps.get_model("chat", "Chat")
    chunk_size = 1000
    query = Chat.objects.filter(experiment_session__isnull=True).order_by("id")
    while True:
        ids = list(query.values_list("id", flat=True)[:chunk_size])
        if not ids:
            break
        Chat.objects.filter(id__in=ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0023_alter_chatattachment_unique_together"),
        ("experiments", "0025_alter_experimentsession_chat"),
    ]

    operations = [
        migrations.RunPython(delete_orphaned_chats, migrations.RunPython.noop),
    ]
