# Generated by Django 5.2.13 on 2026-06-24 09:00

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('annotations', '0009_alter_tag_category'),
        ('chat', '0024_delete_orphaned_chats'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='chatmessage_created_at_idx'),
        ),
    ]
