# Generated by Django 5.2.16 on 2026-09-23 12:08

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("chat", "0028_alter_chatmessage_external_ids"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="chat",
            index=models.Index(fields=["updated_at", "id"], name="chat_updated_at_id_idx"),
        ),
        AddIndexConcurrently(
            model_name="chatmessage",
            index=models.Index(fields=["updated_at", "id"], name="chatmessage_updated_at_id_idx"),
        ),
    ]
